#!/usr/bin/env python3
"""Generate Kids Global Standards Atlas YAML artifacts from curated seeds + world census."""

from __future__ import annotations

from collections import Counter
from datetime import date
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "kids" / "standards"
RETRIEVED = "2026-09-03"
TRACK_STATUS = "DRAFT_INTERNAL"

# ---------------------------------------------------------------------------
# ISO 3166-1 alpha-2 UN members + commonly tracked education systems
# (exhaustive coverage *architecture*; most rows NOT_YET_RESEARCHED)
# ---------------------------------------------------------------------------

COUNTRIES: list[tuple[str, str, str]] = [
    # (iso, name, region)
    # --- Africa ---
    ("DZ", "Algeria", "africa"),
    ("AO", "Angola", "africa"),
    ("BJ", "Benin", "africa"),
    ("BW", "Botswana", "africa"),
    ("BF", "Burkina Faso", "africa"),
    ("BI", "Burundi", "africa"),
    ("CV", "Cabo Verde", "africa"),
    ("CM", "Cameroon", "africa"),
    ("CF", "Central African Republic", "africa"),
    ("TD", "Chad", "africa"),
    ("KM", "Comoros", "africa"),
    ("CG", "Congo", "africa"),
    ("CD", "Democratic Republic of the Congo", "africa"),
    ("CI", "Côte d'Ivoire", "africa"),
    ("DJ", "Djibouti", "africa"),
    ("EG", "Egypt", "africa"),
    ("GQ", "Equatorial Guinea", "africa"),
    ("ER", "Eritrea", "africa"),
    ("SZ", "Eswatini", "africa"),
    ("ET", "Ethiopia", "africa"),
    ("GA", "Gabon", "africa"),
    ("GM", "Gambia", "africa"),
    ("GH", "Ghana", "africa"),
    ("GN", "Guinea", "africa"),
    ("GW", "Guinea-Bissau", "africa"),
    ("KE", "Kenya", "africa"),
    ("LS", "Lesotho", "africa"),
    ("LR", "Liberia", "africa"),
    ("LY", "Libya", "africa"),
    ("MG", "Madagascar", "africa"),
    ("MW", "Malawi", "africa"),
    ("ML", "Mali", "africa"),
    ("MR", "Mauritania", "africa"),
    ("MU", "Mauritius", "africa"),
    ("MA", "Morocco", "africa"),
    ("MZ", "Mozambique", "africa"),
    ("NA", "Namibia", "africa"),
    ("NE", "Niger", "africa"),
    ("NG", "Nigeria", "africa"),
    ("RW", "Rwanda", "africa"),
    ("ST", "Sao Tome and Principe", "africa"),
    ("SN", "Senegal", "africa"),
    ("SC", "Seychelles", "africa"),
    ("SL", "Sierra Leone", "africa"),
    ("SO", "Somalia", "africa"),
    ("ZA", "South Africa", "africa"),
    ("SS", "South Sudan", "africa"),
    ("SD", "Sudan", "africa"),
    ("TZ", "Tanzania", "africa"),
    ("TG", "Togo", "africa"),
    ("TN", "Tunisia", "africa"),
    ("UG", "Uganda", "africa"),
    ("ZM", "Zambia", "africa"),
    ("ZW", "Zimbabwe", "africa"),
    # --- Americas ---
    ("AG", "Antigua and Barbuda", "americas"),
    ("AR", "Argentina", "americas"),
    ("BS", "Bahamas", "americas"),
    ("BB", "Barbados", "americas"),
    ("BZ", "Belize", "americas"),
    ("BO", "Bolivia", "americas"),
    ("BR", "Brazil", "americas"),
    ("CA", "Canada", "americas"),
    ("CL", "Chile", "americas"),
    ("CO", "Colombia", "americas"),
    ("CR", "Costa Rica", "americas"),
    ("CU", "Cuba", "americas"),
    ("DM", "Dominica", "americas"),
    ("DO", "Dominican Republic", "americas"),
    ("EC", "Ecuador", "americas"),
    ("SV", "El Salvador", "americas"),
    ("GD", "Grenada", "americas"),
    ("GT", "Guatemala", "americas"),
    ("GY", "Guyana", "americas"),
    ("HT", "Haiti", "americas"),
    ("HN", "Honduras", "americas"),
    ("JM", "Jamaica", "americas"),
    ("MX", "Mexico", "americas"),
    ("NI", "Nicaragua", "americas"),
    ("PA", "Panama", "americas"),
    ("PY", "Paraguay", "americas"),
    ("PE", "Peru", "americas"),
    ("KN", "Saint Kitts and Nevis", "americas"),
    ("LC", "Saint Lucia", "americas"),
    ("VC", "Saint Vincent and the Grenadines", "americas"),
    ("SR", "Suriname", "americas"),
    ("TT", "Trinidad and Tobago", "americas"),
    ("US", "United States of America", "americas"),
    ("UY", "Uruguay", "americas"),
    ("VE", "Venezuela", "americas"),
    # --- Europe ---
    ("AL", "Albania", "europe"),
    ("AD", "Andorra", "europe"),
    ("AM", "Armenia", "europe"),
    ("AT", "Austria", "europe"),
    ("AZ", "Azerbaijan", "europe"),
    ("BY", "Belarus", "europe"),
    ("BE", "Belgium", "europe"),
    ("BA", "Bosnia and Herzegovina", "europe"),
    ("BG", "Bulgaria", "europe"),
    ("HR", "Croatia", "europe"),
    ("CY", "Cyprus", "europe"),
    ("CZ", "Czechia", "europe"),
    ("DK", "Denmark", "europe"),
    ("EE", "Estonia", "europe"),
    ("FI", "Finland", "europe"),
    ("FR", "France", "europe"),
    ("GE", "Georgia", "europe"),
    ("DE", "Germany", "europe"),
    ("GR", "Greece", "europe"),
    ("HU", "Hungary", "europe"),
    ("IS", "Iceland", "europe"),
    ("IE", "Ireland", "europe"),
    ("IT", "Italy", "europe"),
    ("XK", "Kosovo", "europe"),  # education-system census; not UN membership claim
    ("LV", "Latvia", "europe"),
    ("LI", "Liechtenstein", "europe"),
    ("LT", "Lithuania", "europe"),
    ("LU", "Luxembourg", "europe"),
    ("MT", "Malta", "europe"),
    ("MD", "Moldova", "europe"),
    ("MC", "Monaco", "europe"),
    ("ME", "Montenegro", "europe"),
    ("NL", "Netherlands", "europe"),
    ("MK", "North Macedonia", "europe"),
    ("NO", "Norway", "europe"),
    ("PL", "Poland", "europe"),
    ("PT", "Portugal", "europe"),
    ("RO", "Romania", "europe"),
    ("RU", "Russian Federation", "europe"),
    ("SM", "San Marino", "europe"),
    ("RS", "Serbia", "europe"),
    ("SK", "Slovakia", "europe"),
    ("SI", "Slovenia", "europe"),
    ("ES", "Spain", "europe"),
    ("SE", "Sweden", "europe"),
    ("CH", "Switzerland", "europe"),
    ("TR", "Türkiye", "europe"),
    ("UA", "Ukraine", "europe"),
    ("GB", "United Kingdom", "europe"),
    ("VA", "Holy See", "europe"),
    # --- Middle East ---
    ("BH", "Bahrain", "middle_east"),
    ("IR", "Iran", "middle_east"),
    ("IQ", "Iraq", "middle_east"),
    ("IL", "Israel", "middle_east"),
    ("JO", "Jordan", "middle_east"),
    ("KW", "Kuwait", "middle_east"),
    ("LB", "Lebanon", "middle_east"),
    ("OM", "Oman", "middle_east"),
    ("PS", "State of Palestine", "middle_east"),
    ("QA", "Qatar", "middle_east"),
    ("SA", "Saudi Arabia", "middle_east"),
    ("SY", "Syrian Arab Republic", "middle_east"),
    ("AE", "United Arab Emirates", "middle_east"),
    ("YE", "Yemen", "middle_east"),
    # --- Asia-Pacific ---
    ("AF", "Afghanistan", "asia_pacific"),
    ("AU", "Australia", "asia_pacific"),
    ("BD", "Bangladesh", "asia_pacific"),
    ("BT", "Bhutan", "asia_pacific"),
    ("BN", "Brunei Darussalam", "asia_pacific"),
    ("KH", "Cambodia", "asia_pacific"),
    ("CN", "China", "asia_pacific"),
    ("FJ", "Fiji", "asia_pacific"),
    ("IN", "India", "asia_pacific"),
    ("ID", "Indonesia", "asia_pacific"),
    ("JP", "Japan", "asia_pacific"),
    ("KZ", "Kazakhstan", "asia_pacific"),
    ("KI", "Kiribati", "asia_pacific"),
    ("KG", "Kyrgyzstan", "asia_pacific"),
    ("LA", "Lao People's Democratic Republic", "asia_pacific"),
    ("MY", "Malaysia", "asia_pacific"),
    ("MV", "Maldives", "asia_pacific"),
    ("MH", "Marshall Islands", "asia_pacific"),
    ("FM", "Micronesia", "asia_pacific"),
    ("MN", "Mongolia", "asia_pacific"),
    ("MM", "Myanmar", "asia_pacific"),
    ("NR", "Nauru", "asia_pacific"),
    ("NP", "Nepal", "asia_pacific"),
    ("NZ", "New Zealand", "asia_pacific"),
    ("KP", "Democratic People's Republic of Korea", "asia_pacific"),
    ("KR", "Republic of Korea", "asia_pacific"),
    ("PK", "Pakistan", "asia_pacific"),
    ("PW", "Palau", "asia_pacific"),
    ("PG", "Papua New Guinea", "asia_pacific"),
    ("PH", "Philippines", "asia_pacific"),
    ("WS", "Samoa", "asia_pacific"),
    ("SG", "Singapore", "asia_pacific"),
    ("SB", "Solomon Islands", "asia_pacific"),
    ("LK", "Sri Lanka", "asia_pacific"),
    ("TJ", "Tajikistan", "asia_pacific"),
    ("TH", "Thailand", "asia_pacific"),
    ("TL", "Timor-Leste", "asia_pacific"),
    ("TO", "Tonga", "asia_pacific"),
    ("TM", "Turkmenistan", "asia_pacific"),
    ("TV", "Tuvalu", "asia_pacific"),
    ("UZ", "Uzbekistan", "asia_pacific"),
    ("VU", "Vanuatu", "asia_pacific"),
    ("VN", "Viet Nam", "asia_pacific"),
]

# Subnational education authorities that matter for Kids Edition crosswalks
SUBNATIONAL: list[dict] = [
    # UK nations (England EYFS ≠ Scotland/Wales/NI)
    {
        "jurisdiction_id": "JUR-GB-ENG",
        "iso3166_1": "GB",
        "iso3166_2": "GB-ENG",
        "name": "England",
        "level": "subnational",
        "parent_jurisdiction_id": "JUR-GB",
        "region": "europe",
        "education_authority": "Department for Education (England)",
        "research_status": "OFFICIAL_VERIFIED",
        "framework_ids": ["FW-GB-ENG-EYFS-2026"],
        "notes": "EYFS statutory frameworks apply to England only; do not treat as UK-wide.",
    },
    {
        "jurisdiction_id": "JUR-GB-SCT",
        "iso3166_1": "GB",
        "iso3166_2": "GB-SCT",
        "name": "Scotland",
        "level": "subnational",
        "parent_jurisdiction_id": "JUR-GB",
        "region": "europe",
        "education_authority": "Education Scotland / Scottish Government",
        "research_status": "IDENTIFIED",
        "framework_ids": ["FW-GB-SCT-CFE"],
        "notes": "Curriculum for Excellence + early level; distinct from England EYFS.",
    },
    {
        "jurisdiction_id": "JUR-GB-WLS",
        "iso3166_1": "GB",
        "iso3166_2": "GB-WLS",
        "name": "Wales",
        "level": "subnational",
        "parent_jurisdiction_id": "JUR-GB",
        "region": "europe",
        "education_authority": "Welsh Government / Curriculum for Wales",
        "research_status": "IDENTIFIED",
        "framework_ids": ["FW-GB-WLS-CFW"],
        "notes": "Curriculum for Wales; not EYFS.",
    },
    {
        "jurisdiction_id": "JUR-GB-NIR",
        "iso3166_1": "GB",
        "iso3166_2": "GB-NIR",
        "name": "Northern Ireland",
        "level": "subnational",
        "parent_jurisdiction_id": "JUR-GB",
        "region": "europe",
        "education_authority": "Department of Education (Northern Ireland)",
        "research_status": "IDENTIFIED",
        "framework_ids": ["FW-GB-NIR-CURRICULUM"],
        "notes": "NI curriculum / Foundation Stage; not England EYFS.",
    },
    # Canada provinces/territories
    *[
        {
            "jurisdiction_id": f"JUR-CA-{code}",
            "iso3166_1": "CA",
            "iso3166_2": f"CA-{code}",
            "name": name,
            "level": "subnational",
            "parent_jurisdiction_id": "JUR-CA",
            "region": "americas",
            "education_authority": authority,
            "research_status": status,
            "framework_ids": fws,
            "notes": notes,
        }
        for code, name, authority, status, fws, notes in [
            (
                "ON",
                "Ontario",
                "Ontario Ministry of Education",
                "OFFICIAL_VERIFIED",
                ["FW-CA-ON-KINDERGARTEN-2016"],
                "Kindergarten Program 2016 verified; coding expectations evolving toward 2026 updates — track separately.",
            ),
            ("QC", "Quebec", "Ministère de l'Éducation (Québec)", "TRANSLATION_REQUIRED", [], "French-primary official texts; translation review needed."),
            ("BC", "British Columbia", "BC Ministry of Education and Child Care", "IDENTIFIED", [], "BC Early Learning Framework + curriculum identified; version pin pending."),
            ("AB", "Alberta", "Alberta Education", "NOT_YET_RESEARCHED", [], ""),
            ("MB", "Manitoba", "Manitoba Education and Early Childhood Learning", "NOT_YET_RESEARCHED", [], ""),
            ("SK", "Saskatchewan", "Saskatchewan Ministry of Education", "NOT_YET_RESEARCHED", [], ""),
            ("NS", "Nova Scotia", "Nova Scotia Education and Early Childhood Development", "NOT_YET_RESEARCHED", [], ""),
            ("NB", "New Brunswick", "New Brunswick Department of Education and Early Childhood Development", "NOT_YET_RESEARCHED", [], ""),
            ("NL", "Newfoundland and Labrador", "NL Department of Education", "NOT_YET_RESEARCHED", [], ""),
            ("PE", "Prince Edward Island", "PEI Department of Education and Early Years", "NOT_YET_RESEARCHED", [], ""),
            ("NT", "Northwest Territories", "NWT Education, Culture and Employment", "NOT_YET_RESEARCHED", [], ""),
            ("YT", "Yukon", "Yukon Department of Education", "NOT_YET_RESEARCHED", [], ""),
            ("NU", "Nunavut", "Nunavut Department of Education", "NOT_YET_RESEARCHED", [], ""),
        ]
    ],
    # Australia states/territories (national EYLF + AC; states implement)
    *[
        {
            "jurisdiction_id": f"JUR-AU-{code}",
            "iso3166_1": "AU",
            "iso3166_2": f"AU-{code}",
            "name": name,
            "level": "subnational",
            "parent_jurisdiction_id": "JUR-AU",
            "region": "asia_pacific",
            "education_authority": authority,
            "research_status": "IDENTIFIED",
            "framework_ids": ["FW-AU-EYLF-V2", "FW-AU-AC-V9"],
            "notes": "National EYLF V2.0 + Australian Curriculum v9 apply; state delivery notes NOT_YET_RESEARCHED in depth.",
        }
        for code, name, authority in [
            ("NSW", "New South Wales", "NSW Education"),
            ("VIC", "Victoria", "Victorian Department of Education"),
            ("QLD", "Queensland", "Queensland Department of Education"),
            ("WA", "Western Australia", "WA Department of Education"),
            ("SA", "South Australia", "SA Department for Education"),
            ("TAS", "Tasmania", "Tasmanian Department for Education, Children and Young People"),
            ("ACT", "Australian Capital Territory", "ACT Education Directorate"),
            ("NT", "Northern Territory", "NT Department of Education and Training"),
        ]
    ],
    # US — federal Head Start + state CS/science (census architecture: all 50 + DC)
    *[
        {
            "jurisdiction_id": f"JUR-US-{code}",
            "iso3166_1": "US",
            "iso3166_2": f"US-{code}",
            "name": name,
            "level": "subnational",
            "parent_jurisdiction_id": "JUR-US",
            "region": "americas",
            "education_authority": f"{name} education agency (name pin pending)",
            "research_status": "NOT_YET_RESEARCHED",
            "framework_ids": [],
            "notes": "State CS / early learning standards census row; CSTA/NGSS adoption varies — do not assume.",
        }
        for code, name in [
            ("AL", "Alabama"), ("AK", "Alaska"), ("AZ", "Arizona"), ("AR", "Arkansas"),
            ("CA", "California"), ("CO", "Colorado"), ("CT", "Connecticut"), ("DE", "Delaware"),
            ("DC", "District of Columbia"), ("FL", "Florida"), ("GA", "Georgia"), ("HI", "Hawaii"),
            ("ID", "Idaho"), ("IL", "Illinois"), ("IN", "Indiana"), ("IA", "Iowa"),
            ("KS", "Kansas"), ("KY", "Kentucky"), ("LA", "Louisiana"), ("ME", "Maine"),
            ("MD", "Maryland"), ("MA", "Massachusetts"), ("MI", "Michigan"), ("MN", "Minnesota"),
            ("MS", "Mississippi"), ("MO", "Missouri"), ("MT", "Montana"), ("NE", "Nebraska"),
            ("NV", "Nevada"), ("NH", "New Hampshire"), ("NJ", "New Jersey"), ("NM", "New Mexico"),
            ("NY", "New York"), ("NC", "North Carolina"), ("ND", "North Dakota"), ("OH", "Ohio"),
            ("OK", "Oklahoma"), ("OR", "Oregon"), ("PA", "Pennsylvania"), ("RI", "Rhode Island"),
            ("SC", "South Carolina"), ("SD", "South Dakota"), ("TN", "Tennessee"), ("TX", "Texas"),
            ("UT", "Utah"), ("VT", "Vermont"), ("VA", "Virginia"), ("WA", "Washington"),
            ("WV", "West Virginia"), ("WI", "Wisconsin"), ("WY", "Wyoming"),
        ]
    ],
]

# National overrides for mandatory / priority frameworks
NATIONAL_OVERRIDES: dict[str, dict] = {
    "US": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "U.S. Department of Health & Human Services / ACF (Head Start); state education agencies for K–12",
        "framework_ids": ["FW-US-HS-ELOF", "FW-CSTA-PK12-2026", "FW-US-NGSS"],
        "notes": "Federal Head Start ELOF verified. CSTA 2026 and NGSS are multi-state / voluntary adoption frameworks — not a single national K–12 curriculum.",
    },
    "GB": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "UK nations have distinct education authorities (see subnational rows)",
        "framework_ids": [],
        "notes": "Do not collapse UK nations. England EYFS verified under JUR-GB-ENG.",
    },
    "AU": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "Australian Government Department of Education / ACECQA / ACARA",
        "framework_ids": ["FW-AU-EYLF-V2", "FW-AU-AC-V9"],
        "notes": "EYLF V2.0 (2022) and Australian Curriculum Version 9 verified at national level.",
    },
    "NZ": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "Ministry of Education (New Zealand)",
        "framework_ids": ["FW-NZ-TE-WHARIKI", "FW-NZ-NZC"],
        "notes": "Te Whāriki early learning curriculum + New Zealand Curriculum identified/verified via MoE portals.",
    },
    "FI": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "Finnish National Agency for Education (OPH)",
        "framework_ids": ["FW-FI-ECEC", "FW-FI-BASIC", "FW-FI-DIGITAL"],
        "notes": "ECEC + basic education national core curricula + digital competence materials; Finnish/Swedish primary texts may need TRANSLATION_REQUIRED for deep clause work.",
    },
    "IN": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "National Council of Educational Research and Training (NCERT) / Ministry of Education",
        "framework_ids": ["FW-IN-NCF-FOUNDATIONAL"],
        "notes": "NCF for the Foundational Stage verified as priority baseline.",
    },
    "SG": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "Ministry of Education (Singapore)",
        "framework_ids": ["FW-SG-NEL-2022"],
        "notes": "Nurturing Early Learners (NEL) Framework 2022 verified.",
    },
    "JP": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "Ministry of Education, Culture, Sports, Science and Technology (MEXT)",
        "framework_ids": ["FW-JP-MEXT-COS"],
        "notes": "Courses of Study (kindergarten / elementary) identified via MEXT; deep clause mapping TRANSLATION_REQUIRED.",
    },
    "ZA": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "Department of Basic Education (South Africa)",
        "framework_ids": ["FW-ZA-CAPS", "FW-ZA-CODING-ROBOTICS"],
        "notes": "CAPS verified as national curriculum baseline; Coding and Robotics curriculum status recorded separately.",
    },
    "CA": {
        "research_status": "IDENTIFIED",
        "education_authority": "Provincial/territorial ministries (no single national K–12 curriculum)",
        "framework_ids": [],
        "notes": "Canada education is provincial/territorial. Ontario verified; other provinces mostly NOT_YET_RESEARCHED.",
    },
    "DE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Standing Conference (KMK) + Länder ministries",
        "framework_ids": [],
        "notes": "Federal system; Länder curricula. Deep census NOT_YET_RESEARCHED per Land.",
    },
    "CH": {
        "research_status": "IDENTIFIED",
        "education_authority": "Cantonal education authorities / EDK",
        "framework_ids": [],
        "notes": "Cantonal system; Lehrplan 21 in many German-speaking cantons — TRANSLATION_REQUIRED for depth.",
    },
    "BE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Communities (Flemish / French / German-speaking)",
        "framework_ids": [],
        "notes": "Community-based education systems; not a single national curriculum.",
    },
    "ES": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education + autonomous communities",
        "framework_ids": [],
        "notes": "National framework + autonomous community curricula.",
    },
    "FR": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministère de l'Éducation nationale",
        "framework_ids": [],
        "notes": "Programmes officiels; TRANSLATION_REQUIRED for deep mapping.",
    },
    "KR": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (Republic of Korea)",
        "framework_ids": [],
        "notes": "Nuri curriculum / national curriculum identified; TRANSLATION_REQUIRED for depth.",
    },
    "CN": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (China)",
        "framework_ids": [],
        "notes": "National curriculum standards; TRANSLATION_REQUIRED / ACCESS may vary by document.",
    },
    "BR": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministério da Educação (MEC)",
        "framework_ids": [],
        "notes": "BNCC identified; Portuguese primary — TRANSLATION_REQUIRED for depth.",
    },
    "MX": {
        "research_status": "IDENTIFIED",
        "education_authority": "Secretaría de Educación Pública (SEP)",
        "framework_ids": [],
        "notes": "Nueva Escuela Mexicana / early education frameworks identified; TRANSLATION_REQUIRED.",
    },
    "AE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (UAE) + emirate authorities",
        "framework_ids": [],
        "notes": "Federal + emirate variation; deeper census NOT_YET_RESEARCHED.",
    },
    "SA": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (Saudi Arabia)",
        "framework_ids": [],
        "notes": "National curriculum modernization underway; version pins pending.",
    },
    "EG": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Technical Education (Egypt)",
        "framework_ids": [],
        "notes": "National curriculum identified; Arabic primary — TRANSLATION_REQUIRED.",
    },
    "KE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (Kenya) / KICD",
        "framework_ids": [],
        "notes": "CBC (Competency Based Curriculum) identified; deeper mapping NOT_YET_RESEARCHED.",
    },
    "NG": {
        "research_status": "IDENTIFIED",
        "education_authority": "Federal Ministry of Education (Nigeria)",
        "framework_ids": [],
        "notes": "National education policy / curriculum instruments identified at high level.",
    },
    "GH": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ghana Education Service / NaCCA",
        "framework_ids": [],
        "notes": "Standards-based curriculum identified; deeper mapping NOT_YET_RESEARCHED.",
    },
}


def frameworks() -> list[dict]:
    """Mandatory + priority official framework baseline."""
    return [
        {
            "framework_id": "FW-UNESCO-AI-STUDENTS-2024",
            "title": "AI competency framework for students",
            "authority": "UNESCO",
            "framework_class": "AI_COMPETENCE",
            "version": "2024",
            "effective_from": "2024-08-08",
            "url": "https://www.unesco.org/en/articles/ai-competency-framework-students",
            "license_note": "UNESCO copyright; summarize only — do not paste wholesale",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-GLOBAL-UNESCO"],
            "language": ["en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": [
                "human-centred mindset",
                "ethics of AI",
                "AI techniques and applications",
                "AI system design",
            ],
            "progression_levels": ["Understand", "Apply", "Create"],
            "sdg_link": "SDG 4",
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-UNESCO-AI-TEACHERS-2024",
            "title": "AI competency framework for teachers",
            "authority": "UNESCO",
            "framework_class": "AI_COMPETENCE",
            "version": "2024",
            "effective_from": "2024-08-08",
            "url": "https://www.unesco.org/en/articles/ai-competency-framework-teachers",
            "license_note": "UNESCO copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-GLOBAL-UNESCO"],
            "language": ["en"],
            "age_relevance": ["educator"],
            "summary_domains": [
                "human-centred mindset",
                "ethics of AI",
                "AI foundations and applications",
                "AI pedagogy",
                "AI for professional learning",
            ],
            "progression_levels": ["Acquire", "Deepen", "Create"],
            "sdg_link": "SDG 4",
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-OECD-LEARNING-COMPASS-2030",
            "title": "OECD Learning Compass 2030",
            "authority": "OECD",
            "framework_class": "TRANSVERSAL",
            "version": "2030 framework (evolving; launched 2019)",
            "effective_from": "2019",
            "url": "https://www.oecd.org/en/data/tools/oecd-learning-compass-2030.html",
            "license_note": "OECD materials; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-GLOBAL-OECD"],
            "language": ["en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": [
                "core foundations",
                "knowledge / skills / attitudes and values",
                "transformative competencies",
                "anticipation-action-reflection cycle",
                "student agency",
            ],
            "gaps": ["SOURCE_VERSION_UNCLEAR: evolving concept-note set rather than a single fixed edition PDF"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-US-HS-ELOF",
            "title": "Head Start Early Learning Outcomes Framework: Ages Birth to Five (ELOF)",
            "authority": "U.S. Department of Health & Human Services, Administration for Children and Families",
            "framework_class": "EARLY_YEARS",
            "version": "ELOF (birth to five; replaces 2010 framework)",
            "effective_from": "2015",
            "url": "https://www.headstart.gov/school-readiness/article/head-start-early-learning-outcomes-framework",
            "license_note": "U.S. government work; still do not paste wholesale developmental indicators",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-US"],
            "language": ["en"],
            "age_relevance": ["K2", "K3", "K4", "K5"],
            "summary_domains": [
                "approaches to learning",
                "social and emotional development",
                "language and literacy",
                "cognition",
                "perceptual, motor, and physical development",
            ],
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-CSTA-PK12-2026",
            "title": "2026 CSTA PK–12 Computer Science Standards",
            "authority": "Computer Science Teachers Association (CSTA)",
            "framework_class": "K12_CS",
            "version": "2026",
            "effective_from": "2026",
            "url": "https://csteachers.org/pk12standards/",
            "doi": "https://doi.org/10.1145/3820482",
            "isbn": "979-8-4007-2780-1",
            "license_note": "CSTA license terms apply (attribution, non-commercial share-alike per CSTA site); do not paste wholesale",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-US"],
            "language": ["en"],
            "age_relevance": ["K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": [
                "Algorithms & Design",
                "Programming",
                "Data & Analysis",
                "Systems & Security",
                "Computing & Society",
            ],
            "practice_categories": [
                "Ethics & Social Responsibility",
                "Inclusive Collaboration",
                "Computational Thinking",
                "Human-Centered Design",
            ],
            "notes": "AI content distributed across concepts (not a separate concept). Specialty standards exist for HS; Kids Edition uses foundational PK–early primary grain only.",
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-US-NGSS",
            "title": "Next Generation Science Standards (NGSS)",
            "authority": "NGSS Lead States / nextgenscience.org",
            "framework_class": "K12_SCIENCE",
            "version": "NGSS (K–12; state-adopted where applicable)",
            "effective_from": "2013",
            "url": "https://www.nextgenscience.org/",
            "license_note": "NGSS copyright; summarize three-dimensional structure only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-US"],
            "language": ["en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": [
                "science and engineering practices",
                "crosscutting concepts",
                "disciplinary core ideas",
            ],
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-GB-ENG-EYFS-2026",
            "title": "Early years foundation stage (EYFS) statutory framework (England)",
            "authority": "Department for Education (England)",
            "framework_class": "EARLY_YEARS",
            "version": "Statutory frameworks effective 1 September 2026 (childminders; group and school-based providers)",
            "effective_from": "2026-09-01",
            "url": "https://www.gov.uk/government/publications/early-years-foundation-stage-framework--2",
            "license_note": "Crown copyright / Open Government Licence where applicable; do not paste wholesale",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-GB-ENG"],
            "language": ["en"],
            "age_relevance": ["K2", "K3", "K4", "K5"],
            "summary_domains": [
                "learning and development requirements",
                "safeguarding and welfare requirements",
                "screen-use regard (2026 update noted on GOV.UK)",
            ],
            "notes": "Applies to England only. Scotland / Wales / Northern Ireland use distinct frameworks.",
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-GB-SCT-CFE",
            "title": "Curriculum for Excellence (Scotland) — early level",
            "authority": "Education Scotland / Scottish Government",
            "framework_class": "EARLY_YEARS",
            "version": "SOURCE_VERSION_UNCLEAR",
            "effective_from": None,
            "url": "https://education.gov.scot/",
            "license_note": "Crown copyright / Education Scotland terms",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-GB-SCT"],
            "language": ["en"],
            "age_relevance": ["K3", "K4", "K5", "K6"],
            "summary_domains": ["early level experiences and outcomes"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-GB-WLS-CFW",
            "title": "Curriculum for Wales",
            "authority": "Welsh Government",
            "framework_class": "PRIMARY",
            "version": "SOURCE_VERSION_UNCLEAR",
            "effective_from": None,
            "url": "https://hwb.gov.wales/curriculum-for-wales",
            "license_note": "Welsh Government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-GB-WLS"],
            "language": ["en", "cy"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7"],
            "summary_domains": ["six areas of learning and experience"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-GB-NIR-CURRICULUM",
            "title": "Northern Ireland Curriculum — Foundation Stage",
            "authority": "Department of Education (Northern Ireland) / CCEA",
            "framework_class": "EARLY_YEARS",
            "version": "SOURCE_VERSION_UNCLEAR",
            "effective_from": None,
            "url": "https://ccea.org.uk/",
            "license_note": "CCEA / DENI copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-GB-NIR"],
            "language": ["en"],
            "age_relevance": ["K4", "K5", "K6"],
            "summary_domains": ["Foundation Stage"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-AU-EYLF-V2",
            "title": "Belonging, Being and Becoming: The Early Years Learning Framework for Australia (EYLF) V2.0",
            "authority": "Australian Government Department of Education (approved under NQF; ACECQA)",
            "framework_class": "EARLY_YEARS",
            "version": "V2.0 (2022)",
            "effective_from": "2023",
            "url": "https://www.acecqa.gov.au/nqf/national-law-regulations/approved-learning-frameworks",
            "license_note": "Australian Government copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-AU"],
            "language": ["en"],
            "age_relevance": ["K2", "K3", "K4", "K5"],
            "summary_domains": ["principles", "practices", "learning outcomes"],
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-AU-AC-V9",
            "title": "Australian Curriculum Version 9",
            "authority": "Australian Curriculum, Assessment and Reporting Authority (ACARA)",
            "framework_class": "PRIMARY",
            "version": "Version 9",
            "effective_from": "2022",
            "url": "https://v9.australiancurriculum.edu.au/",
            "license_note": "ACARA copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-AU"],
            "language": ["en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["Digital Technologies", "Science", "general capabilities"],
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-NZ-TE-WHARIKI",
            "title": "Te Whāriki: Early childhood curriculum",
            "authority": "Ministry of Education (New Zealand)",
            "framework_class": "EARLY_YEARS",
            "version": "2017 refresh (commonly cited); confirm PDF edition on MoE portal when deep-mapping",
            "effective_from": "2017",
            "url": "https://www.education.govt.nz/early-childhood/teaching-and-learning/te-whariki",
            "license_note": "Crown copyright NZ; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-NZ"],
            "language": ["en", "mi"],
            "age_relevance": ["K2", "K3", "K4", "K5"],
            "summary_domains": ["principles", "strands", "goals", "learning outcomes"],
            "gaps": ["SOURCE_VERSION_UNCLEAR: pin exact PDF edition before clause-level work"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-NZ-NZC",
            "title": "The New Zealand Curriculum (NZC)",
            "authority": "Ministry of Education (New Zealand)",
            "framework_class": "PRIMARY",
            "version": "SOURCE_VERSION_UNCLEAR (refresh programme ongoing — pin before deep map)",
            "effective_from": None,
            "url": "https://nzcurriculum.tki.org.nz/",
            "license_note": "Crown copyright NZ",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-NZ"],
            "language": ["en", "mi"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["key competencies", "learning areas including technology"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-FI-ECEC",
            "title": "National core curriculum for early childhood education and care (Finland)",
            "authority": "Finnish National Agency for Education (OPH)",
            "framework_class": "EARLY_YEARS",
            "version": "SOURCE_VERSION_UNCLEAR",
            "effective_from": None,
            "url": "https://www.oph.fi/en",
            "license_note": "OPH copyright; Finnish/Swedish originals primary",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-FI"],
            "language": ["fi", "sv", "en"],
            "age_relevance": ["K2", "K3", "K4", "K5"],
            "summary_domains": ["ECEC pedagogical activities"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-FI-BASIC",
            "title": "National core curriculum for basic education (Finland)",
            "authority": "Finnish National Agency for Education (OPH)",
            "framework_class": "PRIMARY",
            "version": "SOURCE_VERSION_UNCLEAR",
            "effective_from": None,
            "url": "https://www.oph.fi/en",
            "license_note": "OPH copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-FI"],
            "language": ["fi", "sv", "en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["transversal competences", "subjects including ICT"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-FI-DIGITAL",
            "title": "Finland digital competence / ICT in education materials (OPH)",
            "authority": "Finnish National Agency for Education (OPH)",
            "framework_class": "DIGITAL_COMPETENCE",
            "version": "SOURCE_VERSION_UNCLEAR",
            "effective_from": None,
            "url": "https://www.oph.fi/en",
            "license_note": "OPH copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-FI"],
            "language": ["fi", "en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["digital competence"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-IN-NCF-FOUNDATIONAL",
            "title": "National Curriculum Framework for the Foundational Stage",
            "authority": "NCERT / Ministry of Education (India)",
            "framework_class": "EARLY_YEARS",
            "version": "NCF-FS (NEP 2020 foundational stage)",
            "effective_from": "2022",
            "url": "https://ncert.nic.in/",
            "license_note": "Government of India / NCERT copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-IN"],
            "language": ["en", "hi"],
            "age_relevance": ["K2", "K3", "K4", "K5", "K6", "K7"],
            "summary_domains": ["foundational literacy and numeracy", "play-based learning", "holistic development"],
            "gaps": ["SOURCE_VERSION_UNCLEAR: pin exact PDF edition hash before clause-level work"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-SG-NEL-2022",
            "title": "Nurturing Early Learners (NEL) Framework 2022",
            "authority": "Ministry of Education (Singapore)",
            "framework_class": "EARLY_YEARS",
            "version": "2022",
            "effective_from": "2022",
            "url": "https://nel.moe.edu.sg/tl/all-resources/nel-framework-2022-/",
            "license_note": "MOE Singapore copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-SG"],
            "language": ["en"],
            "age_relevance": ["K4", "K5", "K6"],
            "summary_domains": ["learning areas", "iTeach principles", "learning dispositions"],
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-JP-MEXT-COS",
            "title": "Courses of Study (kindergarten / elementary) — MEXT",
            "authority": "Ministry of Education, Culture, Sports, Science and Technology (MEXT), Japan",
            "framework_class": "PRIMARY",
            "version": "SOURCE_VERSION_UNCLEAR",
            "effective_from": None,
            "url": "https://www.mext.go.jp/en/",
            "license_note": "MEXT copyright; Japanese primary texts",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-JP"],
            "language": ["ja", "en"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["kindergarten guidelines", "elementary Courses of Study"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-CA-ON-KINDERGARTEN-2016",
            "title": "The Kindergarten Program (Ontario)",
            "authority": "Ontario Ministry of Education",
            "framework_class": "EARLY_YEARS",
            "version": "2016",
            "effective_from": "2016",
            "url": "https://www.ontario.ca/page/ministry-education",
            "license_note": "Queen's Printer for Ontario; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-CA-ON"],
            "language": ["en", "fr"],
            "age_relevance": ["K4", "K5"],
            "summary_domains": ["four frames", "play- and inquiry-based learning"],
            "gaps": ["SOURCE_VERSION_UNCLEAR: 2026 kindergarten refresh announced in secondary reporting — confirm official PDF before remapping"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-ZA-CAPS",
            "title": "Curriculum and Assessment Policy Statement (CAPS)",
            "authority": "Department of Basic Education (South Africa)",
            "framework_class": "PRIMARY",
            "version": "CAPS (subject statements; pin per subject when mapping)",
            "effective_from": None,
            "url": "https://www.education.gov.za/",
            "license_note": "DBE copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-ZA"],
            "language": ["en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["Foundation Phase", "Intermediate Phase subject policies"],
            "gaps": ["SOURCE_VERSION_UNCLEAR: pin per-subject CAPS PDF editions"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-ZA-CODING-ROBOTICS",
            "title": "Coding and Robotics curriculum (South Africa)",
            "authority": "Department of Basic Education (South Africa)",
            "framework_class": "K12_CS",
            "version": "SOURCE_VERSION_UNCLEAR",
            "effective_from": None,
            "url": "https://www.education.gov.za/",
            "license_note": "DBE copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-ZA"],
            "language": ["en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["coding", "robotics"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED", "pin official CAPS Coding and Robotics PDFs by phase"],
            "mandatory_baseline": True,
        },
        # Additional CS/digital competence frameworks (non-mandatory but atlas-relevant)
        {
            "framework_id": "FW-EU-DIGCOMP",
            "title": "DigComp — European Digital Competence Framework for Citizens",
            "authority": "European Commission / Joint Research Centre",
            "framework_class": "DIGITAL_COMPETENCE",
            "version": "DigComp 2.2 (commonly cited); confirm portal edition",
            "effective_from": None,
            "url": "https://joint-research-centre.ec.europa.eu/digcomp_en",
            "license_note": "EU copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-GLOBAL-EU"],
            "language": ["en"],
            "age_relevance": ["B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["information literacy", "communication", "content creation", "safety", "problem solving"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-UNESCO-ICT-CFT",
            "title": "UNESCO ICT Competency Framework for Teachers",
            "authority": "UNESCO",
            "framework_class": "DIGITAL_COMPETENCE",
            "version": "Version 3 (commonly cited)",
            "effective_from": None,
            "url": "https://www.unesco.org/en/digital-education/ict-competency-framework",
            "license_note": "UNESCO copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-GLOBAL-UNESCO"],
            "language": ["en"],
            "age_relevance": ["educator"],
            "summary_domains": ["ICT teacher competencies"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
    ]


def kids_targets() -> list[dict]:
    return [
        {
            "kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "label": "Playful inquiry and noticing",
            "bands": ["K2", "K3", "K4", "K5"],
            "description": "Observe, wonder, try again — foundation for later system thinking.",
        },
        {
            "kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "label": "Algorithmic thinking foundations",
            "bands": ["K4", "K5", "K6", "K7"],
            "description": "Sequences, patterns, and stepwise instructions in play — not formal CS theory.",
        },
        {
            "kids_target_id": "KE-TARGET-DATA-PATTERNS",
            "label": "Data and pattern sense",
            "bands": ["K5", "K6", "K7", "B5", "B6"],
            "description": "Collect, sort, and talk about simple data from everyday experience.",
        },
        {
            "kids_target_id": "KE-TARGET-SYSTEMS-STABILITY",
            "label": "Systems and stability (kid grain)",
            "bands": ["K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "description": "When something 'works' multiple hidden conditions stay OK — age-appropriate Stability Contract.",
        },
        {
            "kids_target_id": "KE-TARGET-DIGITAL-CITIZENSHIP",
            "label": "Digital citizenship and care",
            "bands": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "description": "Kindness, privacy basics, and human agency around tools and AI.",
        },
        {
            "kids_target_id": "KE-TARGET-AI-LITERACY",
            "label": "Age-appropriate AI literacy",
            "bands": ["B5", "B6", "B7", "B8", "B9", "B10"],
            "description": "What AI systems can/can't do; human judgement; informed by UNESCO AI student competencies.",
        },
        {
            "kids_target_id": "KE-TARGET-SCIENCE-PRACTICES",
            "label": "Science and engineering practices (early)",
            "bands": ["K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "description": "Ask, investigate, model, explain — informed by NGSS practices at adjacent grain.",
        },
        {
            "kids_target_id": "KE-TARGET-COMPUTING-SOCIETY",
            "label": "Computing and society",
            "bands": ["K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "description": "How computing shapes communities; ethics and inclusion (CSTA Computing & Society adjacent).",
        },
    ]


def mappings() -> list[dict]:
    """Editorial crosswalks — never certification claims."""
    disclaimer = "Editorial crosswalk only; not a certification or authority endorsement claim."
    return [
        {
            "mapping_id": "MAP-CSTA2026-ALGO-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-CSTA-PK12-2026",
            "from_node": "Algorithms & Design (PK/K–early primary grain)",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["K4", "K5", "K6"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-CSTA2026-DATA-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-CSTA-PK12-2026",
            "from_node": "Data & Analysis (foundational)",
            "to_kids_target_id": "KE-TARGET-DATA-PATTERNS",
            "kids_bands": ["K5", "K6", "K7"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-CSTA2026-SOC-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-CSTA-PK12-2026",
            "from_node": "Computing & Society + Ethics practices",
            "to_kids_target_id": "KE-TARGET-COMPUTING-SOCIETY",
            "kids_bands": ["K6", "K7", "B5", "B6"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-CSTA2026-SYS-KE",
            "relationship": "MAPPED_TO",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-CSTA-PK12-2026",
            "from_node": "Systems & Security (foundational)",
            "to_kids_target_id": "KE-TARGET-SYSTEMS-STABILITY",
            "kids_bands": ["K6", "K7", "B5"],
            "notes": disclaimer + " Proposed kid-grain bridge to Stability Contract language.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-UNESCO-AI-KE",
            "relationship": "INFORMED_BY",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-UNESCO-AI-STUDENTS-2024",
            "from_node": "Human-centred mindset + Ethics of AI",
            "to_kids_target_id": "KE-TARGET-AI-LITERACY",
            "kids_bands": ["B5", "B6", "B7", "B8", "B9", "B10"],
            "notes": disclaimer + " Kids Edition uses simplified progression; not a UNESCO adoption claim.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-UNESCO-AI-CITIZEN-KE",
            "relationship": "INFORMED_BY",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-UNESCO-AI-STUDENTS-2024",
            "from_node": "Citizenship responsibilities in the AI era",
            "to_kids_target_id": "KE-TARGET-DIGITAL-CITIZENSHIP",
            "kids_bands": ["B5", "B6", "B7", "B8"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-OECD-AGENCY-KE",
            "relationship": "INFORMED_BY",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-OECD-LEARNING-COMPASS-2030",
            "from_node": "Student agency + anticipation-action-reflection",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K3", "K4", "K5"],
            "notes": disclaimer + " High-level pedagogical inspiration only.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-ELOF-PLAY-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-US-HS-ELOF",
            "from_node": "Approaches to Learning / Cognition (domain families)",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K2", "K3", "K4"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-NGSS-SCI-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-US-NGSS",
            "from_node": "Science and Engineering Practices (early elementary)",
            "to_kids_target_id": "KE-TARGET-SCIENCE-PRACTICES",
            "kids_bands": ["K5", "K6", "K7", "B5"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-EYFS-PLAY-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-ENG-EYFS-2026",
            "from_node": "Learning and development (play-based early years)",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K2", "K3", "K4", "K5"],
            "notes": disclaimer + " England-only; not UK-wide.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-EYLF-PLAY-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-AU-EYLF-V2",
            "from_node": "Learning outcomes / play practices",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K2", "K3", "K4", "K5"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-AC-DT-KE",
            "relationship": "MAPPED_TO",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-AU-AC-V9",
            "from_node": "Digital Technologies (F–2 grain)",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["K5", "K6", "K7"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-TEWHARIKI-PLAY-KE",
            "relationship": "INFORMED_BY",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-NZ-TE-WHARIKI",
            "from_node": "Strands / learning outcomes (bicultural early learning)",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K2", "K3", "K4", "K5"],
            "notes": disclaimer + " Respect Te Whāriki as a distinct bicultural curriculum — not a CS standards substitute.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-NEL-PLAY-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-SG-NEL-2022",
            "from_node": "NEL learning areas / purposeful play",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K4", "K5", "K6"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-NCF-PLAY-KE",
            "relationship": "MAPPED_TO",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-IN-NCF-FOUNDATIONAL",
            "from_node": "Foundational stage play-based learning",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K2", "K3", "K4", "K5", "K6"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-ON-KG-PLAY-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-CA-ON-KINDERGARTEN-2016",
            "from_node": "Four frames / inquiry",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K4", "K5"],
            "notes": disclaimer,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-CAPS-NYM",
            "relationship": "MAPPED_TO",
            "fidelity": "NOT_YET_MAPPED",
            "from_framework_id": "FW-ZA-CAPS",
            "from_node": "Foundation Phase (subject grain TBD)",
            "to_kids_target_id": "KE-TARGET-SCIENCE-PRACTICES",
            "kids_bands": ["K5", "K6", "K7"],
            "notes": "Placeholder edge — subject PDFs not yet pinned.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-ZA-CODING-NYM",
            "relationship": "MAPPED_TO",
            "fidelity": "NOT_YET_MAPPED",
            "from_framework_id": "FW-ZA-CODING-ROBOTICS",
            "from_node": "Coding and Robotics (phase TBD)",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["B5", "B6", "B7", "B8"],
            "notes": "Awaiting official phase PDF pins.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-JP-COS-NYM",
            "relationship": "MAPPED_TO",
            "fidelity": "NOT_YET_MAPPED",
            "from_framework_id": "FW-JP-MEXT-COS",
            "from_node": "Elementary Courses of Study (ICT-related)",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["K6", "K7", "B5"],
            "notes": "TRANSLATION_REQUIRED before fidelity upgrade.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-FI-ECEC-NYM",
            "relationship": "MAPPED_TO",
            "fidelity": "NOT_YET_MAPPED",
            "from_framework_id": "FW-FI-ECEC",
            "from_node": "ECEC pedagogical activities",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K2", "K3", "K4", "K5"],
            "notes": "TRANSLATION_REQUIRED / version pin pending.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-SCT-CFE-NYM",
            "relationship": "MAPPED_TO",
            "fidelity": "NOT_YET_MAPPED",
            "from_framework_id": "FW-GB-SCT-CFE",
            "from_node": "Early level",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K3", "K4", "K5"],
            "notes": "UK nation distinction preserved; mapping pending.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-DIGCOMP-NYM",
            "relationship": "INFORMED_BY",
            "fidelity": "NOT_YET_MAPPED",
            "from_framework_id": "FW-EU-DIGCOMP",
            "from_node": "DigComp competence areas",
            "to_kids_target_id": "KE-TARGET-DIGITAL-CITIZENSHIP",
            "kids_bands": ["B8", "B9", "B10"],
            "notes": "Adult/citizen framework — kid-grain adaptation not yet designed.",
            "reviewed_on": RETRIEVED,
        },
    ]


def build_jurisdictions() -> list[dict]:
    rows: list[dict] = [
        {
            "jurisdiction_id": "JUR-GLOBAL-UNESCO",
            "iso3166_1": None,
            "iso3166_2": None,
            "name": "UNESCO (transnational)",
            "level": "transnational",
            "parent_jurisdiction_id": None,
            "region": "global",
            "education_authority": "UNESCO",
            "research_status": "OFFICIAL_VERIFIED",
            "framework_ids": [
                "FW-UNESCO-AI-STUDENTS-2024",
                "FW-UNESCO-AI-TEACHERS-2024",
                "FW-UNESCO-ICT-CFT",
            ],
            "notes": "Global reference frameworks under SDG 4 — not a national curriculum.",
            "last_reviewed_on": RETRIEVED,
        },
        {
            "jurisdiction_id": "JUR-GLOBAL-OECD",
            "iso3166_1": None,
            "iso3166_2": None,
            "name": "OECD (transnational)",
            "level": "transnational",
            "parent_jurisdiction_id": None,
            "region": "global",
            "education_authority": "OECD",
            "research_status": "OFFICIAL_VERIFIED",
            "framework_ids": ["FW-OECD-LEARNING-COMPASS-2030"],
            "notes": "Learning Compass is aspirational / evolving — not a curriculum mandate.",
            "last_reviewed_on": RETRIEVED,
        },
        {
            "jurisdiction_id": "JUR-GLOBAL-EU",
            "iso3166_1": None,
            "iso3166_2": None,
            "name": "European Union (transnational competence frameworks)",
            "level": "transnational",
            "parent_jurisdiction_id": None,
            "region": "europe",
            "education_authority": "European Commission",
            "research_status": "IDENTIFIED",
            "framework_ids": ["FW-EU-DIGCOMP"],
            "notes": "DigComp informs member-state digital competence work; not a kids curriculum.",
            "last_reviewed_on": RETRIEVED,
        },
    ]

    for iso, name, region in COUNTRIES:
        ov = NATIONAL_OVERRIDES.get(iso, {})
        rows.append(
            {
                "jurisdiction_id": f"JUR-{iso}",
                "iso3166_1": iso,
                "iso3166_2": None,
                "name": name,
                "level": "national",
                "parent_jurisdiction_id": None,
                "region": region,
                "education_authority": ov.get(
                    "education_authority", f"National education ministry / agency ({name}) — pin pending"
                ),
                "research_status": ov.get("research_status", "NOT_YET_RESEARCHED"),
                "framework_ids": ov.get("framework_ids", []),
                "notes": ov.get("notes", ""),
                "last_reviewed_on": RETRIEVED if ov else None,
            }
        )

    for sn in SUBNATIONAL:
        row = dict(sn)
        row.setdefault("last_reviewed_on", RETRIEVED if sn["research_status"] != "NOT_YET_RESEARCHED" else None)
        rows.append(row)

    return rows


def dump_yaml(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(
            data,
            f,
            sort_keys=False,
            allow_unicode=True,
            width=100,
            default_flow_style=False,
        )


def regional_slices(jurisdictions: list[dict]) -> None:
    by_region: dict[str, list] = {}
    for j in jurisdictions:
        if j["level"] == "transnational":
            continue
        by_region.setdefault(j["region"], []).append(
            {
                "jurisdiction_id": j["jurisdiction_id"],
                "name": j["name"],
                "level": j["level"],
                "research_status": j["research_status"],
                "framework_ids": j.get("framework_ids") or [],
            }
        )
    for region, rows in sorted(by_region.items()):
        counts = Counter(r["research_status"] for r in rows)
        dump_yaml(
            OUT / "regional" / f"{region}.yaml",
            {
                "schema": "kids.standards.regional/v1",
                "region": region,
                "generated_on": RETRIEVED,
                "track_status": TRACK_STATUS,
                "jurisdiction_count": len(rows),
                "status_counts": dict(counts),
                "priority_notes": {
                    "americas": "Ontario verified; US states census scaffolded; LatAm mostly NOT_YET_RESEARCHED.",
                    "europe": "England EYFS verified; other UK nations IDENTIFIED; Nordics/central Europe census open.",
                    "africa": "South Africa CAPS (+ Coding/Robotics) priority; Francophone/Lusophone TRANSLATION_REQUIRED queue.",
                    "middle_east": "High-level IDENTIFIED for UAE/Saudi/Egypt; deep pins pending.",
                    "asia_pacific": "AU/NZ/SG/IN/JP baseline present; ASEAN/Pacific mostly NOT_YET_RESEARCHED.",
                    "global": "N/A",
                }.get(region, ""),
                "jurisdictions": rows,
            },
        )


def coverage_report(jurisdictions: list[dict], sources: list[dict], maps: list[dict]) -> str:
    j_counts = Counter(j["research_status"] for j in jurisdictions)
    m_counts = Counter(m["fidelity"] for m in maps)
    mandatory = [s for s in sources if s.get("mandatory_baseline")]
    lines = [
        "# Global Standards Coverage Report",
        "",
        f"**Generated:** {RETRIEVED}  ",
        f"**Track status:** `{TRACK_STATUS}` (not PUBLICATION_READY)  ",
        f"**Schema:** `kids/standards/STANDARD_MAPPING_SCHEMA.md`  ",
        f"**Base SHA (integration tip):** `ce9cc419841fa0588e30d8d917b048c72f8cc2c0`  ",
        f"**Accepted main:** `82284cd8f41d750ff508cd6ea5bad0a9534d8162`",
        "",
        "## Jurisdiction metrics",
        "",
        f"| Metric | Count |",
        f"| --- | ---: |",
        f"| Jurisdictions total | {len(jurisdictions)} |",
        f"| OFFICIAL_VERIFIED | {j_counts.get('OFFICIAL_VERIFIED', 0)} |",
        f"| IDENTIFIED | {j_counts.get('IDENTIFIED', 0)} |",
        f"| TRANSLATION_REQUIRED | {j_counts.get('TRANSLATION_REQUIRED', 0)} |",
        f"| ACCESS_BLOCKED | {j_counts.get('ACCESS_BLOCKED', 0)} |",
        f"| NOT_YET_RESEARCHED | {j_counts.get('NOT_YET_RESEARCHED', 0)} |",
        "",
        "## Mapping metrics",
        "",
        f"| Fidelity | Count |",
        f"| --- | ---: |",
        f"| EXACT | {m_counts.get('EXACT', 0)} |",
        f"| ADJACENT | {m_counts.get('ADJACENT', 0)} |",
        f"| PROPOSED | {m_counts.get('PROPOSED', 0)} |",
        f"| NO_MAP | {m_counts.get('NO_MAP', 0)} |",
        f"| NOT_YET_MAPPED | {m_counts.get('NOT_YET_MAPPED', 0)} |",
        f"| **Mappings total** | **{len(maps)}** |",
        "",
        "## Mandatory framework baseline status",
        "",
        "| Framework | Authority | Version | Verification | URL | Gaps |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for s in mandatory:
        gaps = "; ".join(s.get("gaps") or []) or "—"
        ver = s.get("verification", "")
        lines.append(
            f"| {s['title']} | {s['authority']} | {s.get('version')} | `{ver}` | {s.get('url')} | {gaps} |"
        )
    lines.extend(
        [
            "",
            "## Honest gaps (priority)",
            "",
            "1. **UK nations:** England EYFS `OFFICIAL_VERIFIED`; Scotland / Wales / NI remain `IDENTIFIED` + `NOT_YET_MAPPED`.",
            "2. **Finland / Japan:** Official portals identified; deep clause work `TRANSLATION_REQUIRED` + version pins unclear.",
            "3. **South Africa Coding & Robotics:** Instrument identified; phase PDF editions not pinned → `NOT_YET_MAPPED`.",
            "4. **Canada:** Ontario kindergarten verified; remaining provinces/territories mostly `NOT_YET_RESEARCHED` (Quebec `TRANSLATION_REQUIRED`).",
            "5. **US states:** Full 50+DC census rows exist as architecture; CS/early-learning adoption research not started (`NOT_YET_RESEARCHED`).",
            "6. **World majority:** Most national rows are intentional `NOT_YET_RESEARCHED` placeholders for exhaustive coverage architecture.",
            "7. **No EXACT maps yet:** Early editorial grain prefers `ADJACENT`/`PROPOSED` over false precision.",
            "8. **Copyright:** No wholesale standards text included; domain-family summaries only.",
            "",
            "## Non-claims",
            "",
            "- Crosswalks are `CROSSWALKED_AGAINST` / `MAPPED_TO` / `INFORMED_BY` — **not** official alignment or certification.",
            "- Presence of a jurisdiction row ≠ completed research.",
            "- This track does not advance Gate 3 or PUBLICATION_READY counts.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    jurisdictions = build_jurisdictions()
    sources = frameworks()
    targets = kids_targets()
    maps = mappings()

    dump_yaml(
        OUT / "GLOBAL_STANDARDS_JURISDICTION_REGISTRY.yaml",
        {
            "schema": "kids.standards.jurisdiction_registry/v1",
            "generated_on": RETRIEVED,
            "track_status": TRACK_STATUS,
            "policy": {
                "official_sources_only": True,
                "forbidden_claims": [
                    "officially aligned",
                    "certified against",
                    "accredited to",
                ],
                "honest_gap_codes": [
                    "TRANSLATION_REQUIRED",
                    "ACCESS_BLOCKED",
                    "NOT_YET_RESEARCHED",
                    "SOURCE_VERSION_UNCLEAR",
                ],
            },
            "counts": {
                "total": len(jurisdictions),
                "by_status": dict(Counter(j["research_status"] for j in jurisdictions)),
                "by_level": dict(Counter(j["level"] for j in jurisdictions)),
                "by_region": dict(Counter(j["region"] for j in jurisdictions)),
            },
            "jurisdictions": jurisdictions,
        },
    )

    dump_yaml(
        OUT / "GLOBAL_STANDARDS_SOURCE_REGISTER.yaml",
        {
            "schema": "kids.standards.source_register/v1",
            "generated_on": RETRIEVED,
            "track_status": TRACK_STATUS,
            "retrieved_on_default": RETRIEVED,
            "framework_count": len(sources),
            "mandatory_baseline_count": sum(1 for s in sources if s.get("mandatory_baseline")),
            "frameworks": sources,
        },
    )

    dump_yaml(
        OUT / "GLOBAL_STANDARDS_ATLAS.yaml",
        {
            "schema": "kids.standards.atlas/v1",
            "generated_on": RETRIEVED,
            "track_status": TRACK_STATUS,
            "disclaimer": (
                "Editorial crosswalks only. Prefer CROSSWALKED_AGAINST / MAPPED_TO / INFORMED_BY. "
                "Never claim official alignment or certification."
            ),
            "kids_targets": targets,
            "mappings": maps,
            "mapping_counts_by_fidelity": dict(Counter(m["fidelity"] for m in maps)),
        },
    )

    regional_slices(jurisdictions)
    (OUT / "GLOBAL_STANDARDS_COVERAGE_REPORT.md").write_text(
        coverage_report(jurisdictions, sources, maps), encoding="utf-8"
    )
    print(f"Wrote atlas artifacts to {OUT}")
    print("Jurisdictions:", len(jurisdictions))
    print("Frameworks:", len(sources))
    print("Mappings:", len(maps))


if __name__ == "__main__":
    main()
