"""Track 2B — Europe exhaustive research seeds for Kids Global Standards Atlas.

Populates portal / framework metadata for European jurisdictions. Editorial
crosswalks only — never certification or official-alignment claims.
"""

from __future__ import annotations

RETRIEVED = "2026-09-03"
DISCLAIMER = "Editorial crosswalk only; not a certification or authority endorsement claim."

# ---------------------------------------------------------------------------
# National overrides — every Europe country previously NOT_YET_RESEARCHED
# advances to at least IDENTIFIED with an authority portal pin.
# ---------------------------------------------------------------------------

EUROPE_NATIONAL_OVERRIDES: dict[str, dict] = {
    "AL": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Sport (Albania)",
        "framework_ids": ["FW-AL-MES-PORTAL"],
        "notes": "Ministry portal identified (arsimi.gov.al). Pre-university curriculum instruments pending edition pin; Eurydice national unit available.",
    },
    "AD": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministeri d'Educació i Ensenyament Superior (Andorra)",
        "framework_ids": ["FW-AD-EDUCACIO-PORTAL"],
        "notes": "Andorran education portal identified. Small-system curriculum; Catalan/French/Spanish — TRANSLATION_REQUIRED for depth.",
    },
    "AM": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Science, Culture and Sport (Armenia)",
        "framework_ids": ["FW-AM-ESCS-PORTAL"],
        "notes": "Ministry portal identified (bot/geo may 403). State curriculum standards; Armenian primary — TRANSLATION_REQUIRED.",
    },
    "AT": {
        "research_status": "IDENTIFIED",
        "education_authority": "Bundesministerium für Bildung, Wissenschaft und Forschung (BMBWF)",
        "framework_ids": ["FW-AT-LEHRPLAENE"],
        "notes": "BMBWF Lehrpläne portal verified. Primary / kindergarten curricula German-primary — TRANSLATION_REQUIRED for clause work.",
    },
    "AZ": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Science and Education (Azerbaijan)",
        "framework_ids": ["FW-AZ-EDU-PORTAL"],
        "notes": "edu.gov.az portal identified. National curriculum modernization; Azerbaijani/Russian — TRANSLATION_REQUIRED.",
    },
    "BY": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (Belarus)",
        "framework_ids": ["FW-BY-EDU-PORTAL"],
        "notes": "edu.gov.by portal identified. State education standards; Russian/Belarusian — TRANSLATION_REQUIRED.",
    },
    "BE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Communities (Flemish / French / German-speaking) education authorities",
        "framework_ids": ["FW-BE-COMMUNITY-SYSTEM"],
        "notes": "No single national curriculum. Flemish GO!/KV, Fédération Wallonie-Bruxelles, and DG systems are distinct — deep pins per community pending.",
    },
    "BA": {
        "research_status": "IDENTIFIED",
        "education_authority": "Entity / canton education ministries (Bosnia and Herzegovina)",
        "framework_ids": ["FW-BA-FRAGMENTED"],
        "notes": "Highly fragmented (FBiH cantons + RS + Brčko). MCP / entity portals identified; no single national kids curriculum.",
    },
    "BG": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Science (Bulgaria)",
        "framework_ids": ["FW-BG-MON-PORTAL"],
        "notes": "MON portal identified (bot may 403). Pre-school and general education state standards; Bulgarian — TRANSLATION_REQUIRED.",
    },
    "HR": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Science, Education and Youth (Croatia)",
        "framework_ids": ["FW-HR-MZO-PORTAL"],
        "notes": "mzo.gov.hr portal verified. Curriculum reform / subject curricula; Croatian — TRANSLATION_REQUIRED for depth.",
    },
    "CY": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Sport and Youth (Cyprus)",
        "framework_ids": ["FW-CY-MOEC-PORTAL"],
        "notes": "moec.gov.cy portal verified. Analytical programmes for primary/pre-primary; Greek — TRANSLATION_REQUIRED.",
    },
    "CZ": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Youth and Sports (Czechia) / NPI",
        "framework_ids": ["FW-CZ-RVP"],
        "notes": "MSMT portal verified. Framework Educational Programmes (RVP) for preschool + basic education; Czech — TRANSLATION_REQUIRED.",
    },
    "DK": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Children and Education (Denmark) / EMU",
        "framework_ids": ["FW-DK-EMU-FFO"],
        "notes": "uvm.dk + emu.dk portals verified. Folkeskole common objectives + Dagtilbud early years; Danish — TRANSLATION_REQUIRED for clause work.",
    },
    "EE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Research (Estonia)",
        "framework_ids": ["FW-EE-NATIONAL-CURRICULUM"],
        "notes": "hm.ee portal verified. National curricula for pre-school and basic education; strong digital competence strand; Estonian — TRANSLATION_REQUIRED for depth.",
    },
    "FI": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "Finnish National Agency for Education (OPH / EDUFI)",
        "framework_ids": ["FW-FI-ECEC", "FW-FI-PREPRIMARY", "FW-FI-BASIC", "FW-FI-DIGITAL"],
        "notes": "ECEC 2022 core curriculum (EN overview + EN PDF), pre-primary core curriculum, basic education 2014 core curriculum, and transversal digital competence materials pinned via oph.fi. Full Finnish/Swedish normative texts may still need TRANSLATION_REQUIRED for clause-level work.",
    },
    "FR": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministère de l'Éducation nationale",
        "framework_ids": ["FW-FR-PROGRAMMES"],
        "notes": "education.gouv.fr programmes officiels (école maternelle + élémentaire) identified; bot may 403. French primary — TRANSLATION_REQUIRED for deep mapping.",
    },
    "GE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Science and Youth (Georgia)",
        "framework_ids": ["FW-GE-MES-PORTAL"],
        "notes": "mes.gov.ge portal verified. National curriculum; Georgian — TRANSLATION_REQUIRED.",
    },
    "DE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Standing Conference of the Ministers of Education and Cultural Affairs (KMK) + 16 Länder ministries",
        "framework_ids": ["FW-DE-KMK-PORTAL"],
        "notes": "Federal education structure: KMK coordinates; curricula are Land-level. All 16 Länder census rows added as JUR-DE-*. Bildungspläne / Lehrpläne TRANSLATION_REQUIRED per Land.",
    },
    "GR": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Religious Affairs and Sports (Greece) / IEP",
        "framework_ids": ["FW-GR-MINEDU-PORTAL"],
        "notes": "minedu.gov.gr portal verified. Preschool and primary programmes; Greek — TRANSLATION_REQUIRED.",
    },
    "HU": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Interior / Education authority + Oktatási Hivatal (Hungary)",
        "framework_ids": ["FW-HU-NAT"],
        "notes": "National Core Curriculum (NAT) + kindergarten programme identified via education system portals; Hungarian — TRANSLATION_REQUIRED. oktatas.hu may time out from some networks.",
    },
    "IS": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Children (Iceland)",
        "framework_ids": ["FW-IS-NATIONAL-CURRICULUM"],
        "notes": "National Curriculum Guide for Preschools / Compulsory Schools identified via government education pages; Icelandic — TRANSLATION_REQUIRED. Specific ministry path may redirect.",
    },
    "IE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Department of Education (Ireland) / NCCA",
        "framework_ids": ["FW-IE-AISTEAR", "FW-IE-PRIMARY"],
        "notes": "Aistear early childhood framework + Primary Curriculum Framework (NCCA) identified. gov.ie Department of Education portal verified; NCCA site may bot-block.",
    },
    "IT": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministero dell'Istruzione e del Merito (Italy)",
        "framework_ids": ["FW-IT-INDICAZIONI"],
        "notes": "miur.gov.it portal verified. Indicazioni nazionali for scuola dell'infanzia and primo ciclo; Italian — TRANSLATION_REQUIRED.",
    },
    "XK": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Science, Technology and Innovation (Kosovo)",
        "framework_ids": ["FW-XK-MASHT-PORTAL"],
        "notes": "masht.rks-gov.net portal verified. Census row for education-system coverage architecture — not a UN membership claim. Curriculum framework; Albanian/Serbian — TRANSLATION_REQUIRED.",
    },
    "LV": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Science (Latvia)",
        "framework_ids": ["FW-LV-IZM-PORTAL"],
        "notes": "izm.gov.lv portal verified. Competence-based curriculum; Latvian — TRANSLATION_REQUIRED.",
    },
    "LI": {
        "research_status": "IDENTIFIED",
        "education_authority": "Schulamt / education authority (Liechtenstein)",
        "framework_ids": ["FW-LI-SCHULAMT"],
        "notes": "National education administration identified (llv.li may bot-block). Small-system Lehrplan; German — TRANSLATION_REQUIRED.",
    },
    "LT": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Science and Sport (Lithuania)",
        "framework_ids": ["FW-LT-SMM-PORTAL"],
        "notes": "smm.lt portal identified (bot may 403). Pre-school and general education curricula; Lithuanian — TRANSLATION_REQUIRED.",
    },
    "LU": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministère de l'Éducation nationale, de l'Enfance et de la Jeunesse (Luxembourg)",
        "framework_ids": ["FW-LU-MEN-PORTAL"],
        "notes": "men.public.lu portal verified. Cycles 1–4 plan d'études; French/German/Luxembourgish — TRANSLATION_REQUIRED.",
    },
    "MT": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry for Education, Sport, Youth, Research and Innovation (Malta)",
        "framework_ids": ["FW-MT-NCF"],
        "notes": "education.gov.mt portal identified (bot may 403). National Curriculum Framework / Learning Outcomes Framework; English/Maltese available.",
    },
    "MD": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Research (Moldova)",
        "framework_ids": ["FW-MD-MEC-PORTAL"],
        "notes": "mec.gov.md portal verified. Curriculum framework; Romanian/Russian — TRANSLATION_REQUIRED.",
    },
    "MC": {
        "research_status": "IDENTIFIED",
        "education_authority": "Direction de l'Éducation nationale, de la Jeunesse et des Sports (Monaco)",
        "framework_ids": ["FW-MC-EDUCATION"],
        "notes": "Monegasque education authority identified (portal path may redirect). Small-system programmes closely related to French programmes; French — TRANSLATION_REQUIRED.",
    },
    "ME": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Science and Innovation (Montenegro)",
        "framework_ids": ["FW-ME-MPS-PORTAL"],
        "notes": "gov.me/mps portal verified. Preschool and primary subject curricula; Montenegrin — TRANSLATION_REQUIRED.",
    },
    "NL": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Culture and Science (OCW) / SLO",
        "framework_ids": ["FW-NL-KERDOELEN"],
        "notes": "OCW + SLO international portal verified. Kerndoelen (core objectives) for primary; early childhood largely municipal. Dutch — TRANSLATION_REQUIRED for depth.",
    },
    "MK": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Science (North Macedonia)",
        "framework_ids": ["FW-MK-MON-PORTAL"],
        "notes": "mon.gov.mk portal verified. National curricula; Macedonian/Albanian — TRANSLATION_REQUIRED.",
    },
    "NO": {
        "research_status": "IDENTIFIED",
        "education_authority": "Norwegian Directorate for Education and Training (Udir)",
        "framework_ids": ["FW-NO-LK20", "FW-NO-RAMMEPLAN"],
        "notes": "udir.no English + læreplanverket portals verified. LK20 subject curricula + Framework Plan for kindergartens (Rammeplan); Norwegian primary texts — TRANSLATION_REQUIRED for clause work.",
    },
    "PL": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of National Education (Poland)",
        "framework_ids": ["FW-PL-PODSTAWA"],
        "notes": "gov.pl/edukacja + Podstawa programowa portal verified. Core curriculum for preschool and primary; Polish — TRANSLATION_REQUIRED.",
    },
    "PT": {
        "research_status": "IDENTIFIED",
        "education_authority": "Direção-Geral da Educação (DGE) / Ministério da Educação (Portugal)",
        "framework_ids": ["FW-PT-DGE-PORTAL"],
        "notes": "dge.mec.pt portal verified. Orientações Curriculares for preschool + Aprendizagens Essenciais for basic education; Portuguese — TRANSLATION_REQUIRED.",
    },
    "RO": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (Romania)",
        "framework_ids": ["FW-RO-EDU-PORTAL"],
        "notes": "edu.ro portal verified. Curriculum for early education and primary; Romanian — TRANSLATION_REQUIRED.",
    },
    "RU": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (Russian Federation)",
        "framework_ids": ["FW-RU-FSES"],
        "notes": "Federal State Educational Standards (FSES/FGOS) for preschool and primary identified at system level; edu.gov.ru may be unreachable from some networks. Russian — TRANSLATION_REQUIRED.",
    },
    "SM": {
        "research_status": "IDENTIFIED",
        "education_authority": "Segreteria di Stato per l'Istruzione (San Marino)",
        "framework_ids": ["FW-SM-ISTRUZIONE"],
        "notes": "San Marino instruction authority identified (portal may time out). Small-system programmes; Italian — TRANSLATION_REQUIRED.",
    },
    "RS": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (Serbia)",
        "framework_ids": ["FW-RS-PROSVETA"],
        "notes": "prosveta.gov.rs portal verified. Preschool Foundations + primary teaching plans; Serbian — TRANSLATION_REQUIRED.",
    },
    "SK": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education, Research, Development and Youth (Slovakia)",
        "framework_ids": ["FW-SK-ISCED"],
        "notes": "minedu.sk portal verified. State educational programmes (ISCED 0–1); Slovak — TRANSLATION_REQUIRED.",
    },
    "SI": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education (Slovenia)",
        "framework_ids": ["FW-SI-KURIKUL"],
        "notes": "gov.si Ministry of Education portal verified. Kindergarten curriculum + primary subject curricula; Slovenian — TRANSLATION_REQUIRED.",
    },
    "ES": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministerio de Educación, Formación Profesional y Deportes + autonomous communities",
        "framework_ids": ["FW-ES-LOMLOE"],
        "notes": "educacionyfp.gob.es portal verified. LOMLOE national framework + community curricula (e.g. infantil / primaria). Spanish — TRANSLATION_REQUIRED for depth; community variation.",
    },
    "SE": {
        "research_status": "IDENTIFIED",
        "education_authority": "Skolverket (Swedish National Agency for Education)",
        "framework_ids": ["FW-SE-LPFÖ", "FW-SE-LGR"],
        "notes": "skolverket.se English + förskola läroplan portals verified. Lpfö 18 (preschool) + Lgr 22 (compulsory school); Swedish — TRANSLATION_REQUIRED for clause work.",
    },
    "CH": {
        "research_status": "IDENTIFIED",
        "education_authority": "Cantonal education authorities / Swiss Conference of Cantonal Ministers of Education (EDK)",
        "framework_ids": ["FW-CH-LEHRPLAN21"],
        "notes": "edk.ch portal verified. Lehrplan 21 (German-speaking cantons), Plan d'études romand, piano di studio — cantonal. TRANSLATION_REQUIRED for depth.",
    },
    "TR": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of National Education (Türkiye) — MEB",
        "framework_ids": ["FW-TR-MEB-PORTAL"],
        "notes": "meb.gov.tr portal verified. Preschool education programme + primary curricula; Turkish — TRANSLATION_REQUIRED.",
    },
    "UA": {
        "research_status": "IDENTIFIED",
        "education_authority": "Ministry of Education and Science (Ukraine)",
        "framework_ids": ["FW-UA-NUS"],
        "notes": "New Ukrainian School (NUS) reform curricula identified; mon.gov.ua may bot-block. Ukrainian — TRANSLATION_REQUIRED.",
    },
    "GB": {
        "research_status": "OFFICIAL_VERIFIED",
        "education_authority": "UK nations have distinct education authorities (see JUR-GB-ENG/SCT/WLS/NIR)",
        "framework_ids": [],
        "notes": "Do not collapse UK nations. England: EYFS 2026 + primary National Curriculum (incl. computing PoS) verified. Scotland CfE, Curriculum for Wales, and NI Foundation Stage researched as distinct systems.",
    },
    "VA": {
        "research_status": "IDENTIFIED",
        "education_authority": "Holy See / Vatican City State education administration",
        "framework_ids": ["FW-VA-VATICAN-PORTAL"],
        "notes": "vatican.va portal verified. Micro-state / ecclesiastical education context; limited public kids curriculum corpus — gap honest.",
    },
}


GERMANY_LANDER: list[tuple[str, str, str]] = [
    ("BW", "Baden-Württemberg", "Ministerium für Kultus, Jugend und Sport Baden-Württemberg"),
    ("BY", "Bavaria", "Bayerisches Staatsministerium für Unterricht und Kultus"),
    ("BE", "Berlin", "Senatsverwaltung für Bildung, Jugend und Familie (Berlin)"),
    ("BB", "Brandenburg", "Ministerium für Bildung, Jugend und Sport Brandenburg"),
    ("HB", "Bremen", "Die Senatorin für Kinder und Bildung (Bremen)"),
    ("HH", "Hamburg", "Behörde für Schule und Berufsbildung (Hamburg)"),
    ("HE", "Hesse", "Hessisches Kultusministerium"),
    ("MV", "Mecklenburg-Western Pomerania", "Ministerium für Bildung und Kindertagesförderung Mecklenburg-Vorpommern"),
    ("NI", "Lower Saxony", "Niedersächsisches Kultusministerium"),
    ("NW", "North Rhine-Westphalia", "Ministerium für Schule und Bildung des Landes Nordrhein-Westfalen"),
    ("RP", "Rhineland-Palatinate", "Ministerium für Bildung Rheinland-Pfalz"),
    ("SL", "Saarland", "Ministerium für Bildung und Kultur Saarland"),
    ("SN", "Saxony", "Sächsisches Staatsministerium für Kultus"),
    ("ST", "Saxony-Anhalt", "Ministerium für Bildung Sachsen-Anhalt"),
    ("SH", "Schleswig-Holstein", "Ministerium für Allgemeine und Berufliche Bildung, Wissenschaft, Forschung und Kultur Schleswig-Holstein"),
    ("TH", "Thuringia", "Thüringer Ministerium für Bildung, Wissenschaft und Kultur"),
]


def germany_lander_rows() -> list[dict]:
    rows = []
    for code, name, authority in GERMANY_LANDER:
        rows.append(
            {
                "jurisdiction_id": f"JUR-DE-{code}",
                "iso3166_1": "DE",
                "iso3166_2": f"DE-{code}",
                "name": name,
                "level": "subnational",
                "parent_jurisdiction_id": "JUR-DE",
                "region": "europe",
                "education_authority": authority,
                "research_status": "IDENTIFIED",
                "framework_ids": ["FW-DE-KMK-PORTAL"],
                "notes": (
                    "Land education ministry identified within KMK federal structure. "
                    "Land Bildungsplan / Lehrplan edition pin + TRANSLATION_REQUIRED before deep map. "
                    "KMK English overview: https://www.kmk.org/kmk/information-in-english.html"
                ),
                "last_reviewed_on": RETRIEVED,
            }
        )
    return rows


def uk_nation_row_updates() -> dict[str, dict]:
    """Replace SUBNATIONAL UK nation rows with deepened research."""
    return {
        "JUR-GB-ENG": {
            "jurisdiction_id": "JUR-GB-ENG",
            "iso3166_1": "GB",
            "iso3166_2": "GB-ENG",
            "name": "England",
            "level": "subnational",
            "parent_jurisdiction_id": "JUR-GB",
            "region": "europe",
            "education_authority": "Department for Education (England)",
            "research_status": "OFFICIAL_VERIFIED",
            "framework_ids": [
                "FW-GB-ENG-EYFS-2026",
                "FW-GB-ENG-NC-PRIMARY",
                "FW-GB-ENG-NC-COMPUTING",
            ],
            "notes": (
                "EYFS statutory frameworks (effective 1 Sep 2026) + National Curriculum primary "
                "(DFE-00178-2013, last updated 6 May 2015) + Computing programmes of study "
                "(DFE-00171-2013) verified on GOV.UK. England-only — not UK-wide."
            ),
            "last_reviewed_on": RETRIEVED,
        },
        "JUR-GB-SCT": {
            "jurisdiction_id": "JUR-GB-SCT",
            "iso3166_1": "GB",
            "iso3166_2": "GB-SCT",
            "name": "Scotland",
            "level": "subnational",
            "parent_jurisdiction_id": "JUR-GB",
            "region": "europe",
            "education_authority": "Education Scotland / Scottish Government",
            "research_status": "OFFICIAL_VERIFIED",
            "framework_ids": ["FW-GB-SCT-CFE"],
            "notes": (
                "Curriculum for Excellence Experiences and Outcomes + Early Level Benchmarks "
                "verified via education.gov.scot. Distinct from England EYFS. "
                "Realising the Ambition supports ELC practice."
            ),
            "last_reviewed_on": RETRIEVED,
        },
        "JUR-GB-WLS": {
            "jurisdiction_id": "JUR-GB-WLS",
            "iso3166_1": "GB",
            "iso3166_2": "GB-WLS",
            "name": "Wales",
            "level": "subnational",
            "parent_jurisdiction_id": "JUR-GB",
            "region": "europe",
            "education_authority": "Welsh Government / Curriculum for Wales",
            "research_status": "OFFICIAL_VERIFIED",
            "framework_ids": ["FW-GB-WLS-CFW"],
            "notes": (
                "Curriculum for Wales Framework (Curriculum and Assessment (Wales) Act 2021) "
                "+ Statements of What Matters Code (2023 update) pinned. Six AoLE including "
                "Science and Technology. Not EYFS. Hwb portal may bot-block automated fetches."
            ),
            "last_reviewed_on": RETRIEVED,
        },
        "JUR-GB-NIR": {
            "jurisdiction_id": "JUR-GB-NIR",
            "iso3166_1": "GB",
            "iso3166_2": "GB-NIR",
            "name": "Northern Ireland",
            "level": "subnational",
            "parent_jurisdiction_id": "JUR-GB",
            "region": "europe",
            "education_authority": "Department of Education (Northern Ireland) / CCEA",
            "research_status": "OFFICIAL_VERIFIED",
            "framework_ids": ["FW-GB-NIR-CURRICULUM"],
            "notes": (
                "NI Curriculum Primary / Foundation Stage (P1–P2) Areas of Learning + Using ICT "
                "cross-curricular skill verified via CCEA + education-ni.gov.uk. Not England EYFS. "
                "CCEA portal may bot-block automated fetches."
            ),
            "last_reviewed_on": RETRIEVED,
        },
    }


def europe_transnational_rows() -> list[dict]:
    return [
        {
            "jurisdiction_id": "JUR-GLOBAL-EU",
            "iso3166_1": None,
            "iso3166_2": None,
            "name": "European Union (transnational competence frameworks)",
            "level": "transnational",
            "parent_jurisdiction_id": None,
            "region": "europe",
            "education_authority": "European Commission / Joint Research Centre",
            "research_status": "OFFICIAL_VERIFIED",
            "framework_ids": ["FW-EU-DIGCOMP"],
            "notes": (
                "DigComp 2.2 (JRC128415, 2022) version-pinned via Publications Office / JRC. "
                "DigComp 3.0 announced Nov 2025 — track separately before remapping. "
                "Not a national kids curriculum; informs member-state digital competence work. "
                "Eurydice national system descriptions: https://eurydice.eacea.ec.europa.eu/eurypedia"
            ),
            "last_reviewed_on": RETRIEVED,
        },
        {
            "jurisdiction_id": "JUR-GLOBAL-IB",
            "iso3166_1": None,
            "iso3166_2": None,
            "name": "International Baccalaureate (institutional)",
            "level": "institutional",
            "parent_jurisdiction_id": None,
            "region": "global",
            "education_authority": "International Baccalaureate Organization (IBO)",
            "research_status": "IDENTIFIED",
            "framework_ids": ["FW-IB-PYP-PUBLIC"],
            "notes": (
                "IB PYP public framework elements (learner / learning and teaching / learning community; "
                "six transdisciplinary themes; agency) recorded from public IBO programme pages. "
                "Full PYP documentation is licensed to authorised schools — do not paste wholesale. "
                "ibo.org may bot-block automated fetches."
            ),
            "last_reviewed_on": RETRIEVED,
        },
    ]


def _portal_fw(
    framework_id: str,
    title: str,
    authority: str,
    url: str,
    jurisdiction_id: str,
    framework_class: str = "OTHER",
    language: list[str] | None = None,
    summary_domains: list[str] | None = None,
    gaps: list[str] | None = None,
    verification: str = "IDENTIFIED",
    version: str = "SOURCE_VERSION_UNCLEAR",
    notes: str | None = None,
    age_relevance: list[str] | None = None,
) -> dict:
    return {
        "framework_id": framework_id,
        "title": title,
        "authority": authority,
        "framework_class": framework_class,
        "version": version,
        "effective_from": None,
        "url": url,
        "license_note": "Official authority copyright; summarize domain families only — do not paste wholesale",
        "retrieved_on": RETRIEVED,
        "verification": verification,
        "jurisdiction_ids": [jurisdiction_id],
        "language": language or ["en"],
        "age_relevance": age_relevance or ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
        "summary_domains": summary_domains or ["curriculum portal / framework entry point"],
        "gaps": gaps or ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
        "notes": notes,
        "mandatory_baseline": False,
    }


def europe_extra_frameworks() -> list[dict]:
    """New frameworks for England primary NC, Finland pre-primary, IB PYP, DE KMK, portals."""
    fws: list[dict] = [
        {
            "framework_id": "FW-GB-ENG-NC-PRIMARY",
            "title": "National curriculum in England: primary curriculum (key stages 1–2)",
            "authority": "Department for Education (England)",
            "framework_class": "PRIMARY",
            "version": "DFE-00178-2013 (published 11 Sep 2013; last updated 6 May 2015)",
            "effective_from": "2014-09-01",
            "url": "https://www.gov.uk/government/publications/national-curriculum-in-england-primary-curriculum",
            "license_note": "Crown copyright / Open Government Licence where applicable; do not paste wholesale",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-GB-ENG"],
            "language": ["en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": [
                "English",
                "mathematics",
                "science",
                "computing",
                "design and technology",
                "art and design",
                "geography",
                "history",
                "music",
                "physical education",
                "languages (KS2)",
            ],
            "notes": "Statutory for LA-maintained primary schools in England. Academies/free schools follow different statutory routes but often teach NC content.",
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-GB-ENG-NC-COMPUTING",
            "title": "National curriculum in England: computing programmes of study",
            "authority": "Department for Education (England)",
            "framework_class": "K12_CS",
            "version": "DFE-00171-2013 (KS1–2 PDF; published 11 Sep 2013)",
            "effective_from": "2014-09-01",
            "url": "https://www.gov.uk/government/publications/national-curriculum-in-england-computing-programmes-of-study",
            "license_note": "Crown copyright / Open Government Licence where applicable; do not paste wholesale",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-GB-ENG"],
            "language": ["en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": [
                "computer science (algorithms, programming, logical reasoning)",
                "information technology",
                "digital literacy / e-safety",
                "KS1 create and debug simple programs",
                "KS2 sequence selection repetition; networks; data",
            ],
            "notes": "England-only computing PoS. Summarized at strand/outcome-family grain for Kids Edition crosswalk — not a DfE endorsement.",
            "gaps": [],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-FI-PREPRIMARY",
            "title": "National core curriculum for pre-primary education (Finland)",
            "authority": "Finnish National Agency for Education (OPH)",
            "framework_class": "EARLY_YEARS",
            "version": "2014 national core curriculum for pre-primary education (commonly cited; confirm ePerusteet edition)",
            "effective_from": "2016",
            "url": "https://www.oph.fi/en/education-system/early-childhood-education-and-care-finland",
            "license_note": "OPH copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-FI"],
            "language": ["fi", "sv", "en"],
            "age_relevance": ["K5", "K6"],
            "summary_domains": [
                "pre-primary as part of ECEC continuum",
                "transversal competences bridge to basic education",
                "play-based learning",
                "local curriculum compliance with national norm",
            ],
            "notes": "Pre-primary is regulated under the Basic Education Act and linked to ECEC + basic education core curricula. English overview pages verified; full Finnish/Swedish norm may need TRANSLATION_REQUIRED for clause work.",
            "gaps": ["TRANSLATION_REQUIRED: full Finnish/Swedish normative PDF for clause-level work"],
            "mandatory_baseline": True,
        },
        {
            "framework_id": "FW-DE-KMK-PORTAL",
            "title": "KMK — Standing Conference information portal (Germany federal coordination)",
            "authority": "Kultusministerkonferenz (KMK)",
            "framework_class": "OTHER",
            "version": "KMK portal (ongoing; not a single national curriculum PDF)",
            "effective_from": None,
            "url": "https://www.kmk.org/kmk/information-in-english.html",
            "license_note": "KMK copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "OFFICIAL_VERIFIED",
            "jurisdiction_ids": ["JUR-DE"] + [f"JUR-DE-{c}" for c, _, _ in GERMANY_LANDER],
            "language": ["de", "en"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": [
                "Länder responsibility for curricula",
                "KMK coordination / agreements",
                "early childhood and general education structure",
            ],
            "notes": "Germany has no single national kids curriculum. This portal pins the federal coordination layer; Land Lehrpläne are separate.",
            "gaps": ["NOT_YET_MAPPED: Land-level Lehrplan edition pins pending"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-IB-PYP-PUBLIC",
            "title": "IB Primary Years Programme (PYP) — public framework elements",
            "authority": "International Baccalaureate Organization (IBO)",
            "framework_class": "TRANSVERSAL",
            "version": "PYP public programme overview (framework pillars + transdisciplinary themes; licensed docs not reproduced)",
            "effective_from": None,
            "url": "https://www.ibo.org/programmes/primary-years-programme/",
            "license_note": "IBO copyright; public marketing/overview pages only — do not reproduce licensed PYP curriculum documents",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-GLOBAL-IB"],
            "language": ["en"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": [
                "agency / self-efficacy / action",
                "learner; learning and teaching; learning community",
                "six transdisciplinary themes (programme of inquiry)",
                "inquiry-based conceptual understanding",
                "IB learner profile attributes (public)",
            ],
            "notes": "Public elements only. Theme descriptor updates (announced for school transition by Sep 2027) — pin when deep-mapping. Not a national curriculum.",
            "gaps": ["ACCESS_BLOCKED / licensed corpus: full PYP docs behind school authorisation", "SOURCE_VERSION_UNCLEAR: public overview vs licensed edition"],
            "mandatory_baseline": False,
        },
        # Priority national instruments with clearer portals
        {
            "framework_id": "FW-IE-AISTEAR",
            "title": "Aistear: the Early Childhood Curriculum Framework (Ireland)",
            "authority": "National Council for Curriculum and Assessment (NCCA)",
            "framework_class": "EARLY_YEARS",
            "version": "Aistear framework (NCCA; confirm current portal edition)",
            "effective_from": None,
            "url": "https://ncca.ie/",
            "license_note": "NCCA copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-IE"],
            "language": ["en", "ga"],
            "age_relevance": ["K2", "K3", "K4", "K5"],
            "summary_domains": ["well-being", "identity and belonging", "communicating", "exploring and thinking"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-IE-PRIMARY",
            "title": "Primary Curriculum Framework (Ireland)",
            "authority": "NCCA / Department of Education (Ireland)",
            "framework_class": "PRIMARY",
            "version": "Primary Curriculum Framework (redevelopment programme — pin PDF edition)",
            "effective_from": None,
            "url": "https://www.gov.ie/en/organisation/department-of-education/",
            "license_note": "Government of Ireland / NCCA copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-IE"],
            "language": ["en", "ga"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["primary curriculum areas", "STEM / digital learning (grain TBD)"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-NO-RAMMEPLAN",
            "title": "Framework Plan for Kindergartens (Rammeplan) — Norway",
            "authority": "Norwegian Directorate for Education and Training (Udir)",
            "framework_class": "EARLY_YEARS",
            "version": "Framework Plan for the content and tasks of kindergartens (pin PDF edition on udir.no)",
            "effective_from": None,
            "url": "https://www.udir.no/in-english/",
            "license_note": "Udir copyright; summarize only",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-NO"],
            "language": ["no", "en"],
            "age_relevance": ["K2", "K3", "K4", "K5"],
            "summary_domains": ["care play and learning", "kindergarten subject areas", "digital practice (high-level)"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "TRANSLATION_REQUIRED", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-NO-LK20",
            "title": "LK20 subject curricula (Norway)",
            "authority": "Norwegian Directorate for Education and Training (Udir)",
            "framework_class": "PRIMARY",
            "version": "LK20 (curriculum renewal; pin subject pages)",
            "effective_from": "2020",
            "url": "https://www.udir.no/laring-og-trivsel/lareplanverket/",
            "license_note": "Udir copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-NO"],
            "language": ["no", "en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["core curriculum values", "subject curricula", "digital skills as basic skill"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "TRANSLATION_REQUIRED", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-SE-LPFÖ",
            "title": "Curriculum for the Preschool (Lpfö 18) — Sweden",
            "authority": "Skolverket",
            "framework_class": "EARLY_YEARS",
            "version": "Lpfö 18 (pin current Skolverket PDF)",
            "effective_from": "2019",
            "url": "https://www.skolverket.se/undervisning/forskolan/laroplan-for-forskolan",
            "license_note": "Skolverket copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-SE"],
            "language": ["sv", "en"],
            "age_relevance": ["K2", "K3", "K4", "K5"],
            "summary_domains": ["preschool goals", "care development learning", "digital tools (high-level)"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "TRANSLATION_REQUIRED", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-SE-LGR",
            "title": "Curriculum for the Compulsory School (Lgr) — Sweden",
            "authority": "Skolverket",
            "framework_class": "PRIMARY",
            "version": "Lgr 22 (commonly cited; pin Skolverket edition)",
            "effective_from": "2022",
            "url": "https://www.skolverket.se/andra-sprak-other-languages/english-engelska",
            "license_note": "Skolverket copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-SE"],
            "language": ["sv", "en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["compulsory school subjects", "digital competence"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "TRANSLATION_REQUIRED", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-CH-LEHRPLAN21",
            "title": "Lehrplan 21 (German-speaking Swiss cantons) + EDK coordination",
            "authority": "EDK / participating cantons",
            "framework_class": "PRIMARY",
            "version": "Lehrplan 21 (cantonal adoption varies)",
            "effective_from": None,
            "url": "https://www.edk.ch/en",
            "license_note": "Cantonal / EDK copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-CH"],
            "language": ["de", "fr", "it", "en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["Medien und Informatik", "subject areas", "cycle structure"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-ES-LOMLOE",
            "title": "LOMLOE curriculum framework (Spain) — early childhood / primary",
            "authority": "Ministerio de Educación, Formación Profesional y Deportes",
            "framework_class": "PRIMARY",
            "version": "LOMLOE implementing decrees (pin per stage; community curricula vary)",
            "effective_from": None,
            "url": "https://www.educacionyfp.gob.es/",
            "license_note": "Spanish government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-ES"],
            "language": ["es"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "summary_domains": ["educación infantil", "educación primaria", "digital competence key competence"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-FR-PROGRAMMES",
            "title": "Programmes officiels — école maternelle et élémentaire (France)",
            "authority": "Ministère de l'Éducation nationale",
            "framework_class": "PRIMARY",
            "version": "Programmes en vigueur (pin BOEN edition dates)",
            "effective_from": None,
            "url": "https://www.education.gouv.fr/",
            "license_note": "French government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-FR"],
            "language": ["fr"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "summary_domains": ["maternelle domaines", "cycle 2–3 programmes", "enseignement moral et civique / numérique (high-level)"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-NL-KERDOELEN",
            "title": "Kerndoelen (core objectives) — primary education Netherlands",
            "authority": "OCW / SLO",
            "framework_class": "PRIMARY",
            "version": "Kerndoelen (pin current SLO / OCW publication)",
            "effective_from": None,
            "url": "https://www.slo.nl/international/",
            "license_note": "Dutch government / SLO copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-NL"],
            "language": ["nl", "en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["Dutch primary core objectives", "digital literacy developments (grain TBD)"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-AT-LEHRPLAENE",
            "title": "Lehrpläne — Austria (BMBWF)",
            "authority": "BMBWF",
            "framework_class": "PRIMARY",
            "version": "Lehrpläne Volksschule / elementare Bildung (pin current BMBWF pages)",
            "effective_from": None,
            "url": "https://www.bmbwf.gv.at/Themen/schule/schulpraxis/lp.html",
            "license_note": "Austrian government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-AT"],
            "language": ["de"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "summary_domains": ["Volksschule Lehrplan", "elementare Bildung", "digitale Grundbildung (high-level)"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-DK-EMU-FFO",
            "title": "Denmark — Folkeskole common objectives / Dagtilbud early years (EMU)",
            "authority": "Ministry of Children and Education (Denmark)",
            "framework_class": "PRIMARY",
            "version": "Fælles Mål / Dagtilbudsloven materials (pin EMU editions)",
            "effective_from": None,
            "url": "https://emu.dk/",
            "license_note": "Danish government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-DK"],
            "language": ["da"],
            "age_relevance": ["K2", "K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "summary_domains": ["Fælles Mål subject objectives", "early childhood pedagogical curriculum"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-EE-NATIONAL-CURRICULUM",
            "title": "Estonia national curricula (pre-school + basic)",
            "authority": "Ministry of Education and Research (Estonia)",
            "framework_class": "PRIMARY",
            "version": "National curricula (pin Riigi Teataja / HM editions)",
            "effective_from": None,
            "url": "https://www.hm.ee/en",
            "license_note": "Estonian government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-EE"],
            "language": ["et", "en"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["pre-school curriculum", "basic school national curriculum", "digital competence"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-PL-PODSTAWA",
            "title": "Podstawa programowa — Poland",
            "authority": "Ministry of National Education (Poland)",
            "framework_class": "PRIMARY",
            "version": "Podstawa programowa (pin current gov.pl PDFs by stage)",
            "effective_from": None,
            "url": "https://www.gov.pl/web/edukacja/podstawa-programowa",
            "license_note": "Polish government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-PL"],
            "language": ["pl"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "summary_domains": ["preschool core curriculum", "primary core curriculum", "informatics (high-level)"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-IT-INDICAZIONI",
            "title": "Indicazioni nazionali — scuola dell'infanzia e primo ciclo (Italy)",
            "authority": "Ministero dell'Istruzione e del Merito",
            "framework_class": "PRIMARY",
            "version": "Indicazioni nazionali (pin current MIUR edition)",
            "effective_from": None,
            "url": "https://www.miur.gov.it/web/guest/scuola",
            "license_note": "Italian government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-IT"],
            "language": ["it"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "summary_domains": ["campi di esperienza", "discipline del primo ciclo", "competenze digitali (high-level)"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-CZ-RVP",
            "title": "Framework Educational Programmes (RVP) — Czechia",
            "authority": "Ministry of Education, Youth and Sports / NPI",
            "framework_class": "PRIMARY",
            "version": "RVP PV + RVP ZV (pin current editions)",
            "effective_from": None,
            "url": "https://www.msmt.cz/",
            "license_note": "Czech government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-CZ"],
            "language": ["cs"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "summary_domains": ["preschool RVP", "basic education RVP", "ICT educational area"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-PT-DGE-PORTAL",
            "title": "Portugal DGE curriculum orientations / Aprendizagens Essenciais",
            "authority": "Direção-Geral da Educação",
            "framework_class": "PRIMARY",
            "version": "Orientações Curriculares + Aprendizagens Essenciais (pin PDFs)",
            "effective_from": None,
            "url": "https://www.dge.mec.pt/",
            "license_note": "Portuguese government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-PT"],
            "language": ["pt"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "summary_domains": ["educação pré-escolar", "1º ciclo", "cidadania e desenvolvimento / digital (high-level)"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-UA-NUS",
            "title": "New Ukrainian School (NUS) curricula",
            "authority": "Ministry of Education and Science (Ukraine)",
            "framework_class": "PRIMARY",
            "version": "NUS state standards / model curricula (pin editions)",
            "effective_from": None,
            "url": "https://mon.gov.ua/eng",
            "license_note": "Ukrainian government copyright",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-UA"],
            "language": ["uk", "en"],
            "age_relevance": ["K5", "K6", "K7", "B5", "B6", "B7", "B8", "B9", "B10"],
            "summary_domains": ["NUS competency-based primary", "ICT / digital competence"],
            "gaps": ["TRANSLATION_REQUIRED", "SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "mandatory_baseline": False,
        },
        {
            "framework_id": "FW-BE-COMMUNITY-SYSTEM",
            "title": "Belgium — community education systems (entry point)",
            "authority": "Flemish / French / German-speaking Community education authorities",
            "framework_class": "OTHER",
            "version": "Community-specific curricula (no single national instrument)",
            "effective_from": None,
            "url": "https://eurydice.eacea.ec.europa.eu/eurypedia",
            "license_note": "Community authority copyright; Eurydice is descriptive",
            "retrieved_on": RETRIEVED,
            "verification": "IDENTIFIED",
            "jurisdiction_ids": ["JUR-BE"],
            "language": ["nl", "fr", "de", "en"],
            "age_relevance": ["K3", "K4", "K5", "K6", "K7"],
            "summary_domains": ["community curricula", "Eurydice system description"],
            "gaps": ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            "notes": "Use Eurydice Belgium pages as research index; deep pins require per-community follow-up.",
            "mandatory_baseline": False,
        },
    ]

    # Lightweight portal stubs for remaining Europe rows (honest IDENTIFIED coverage)
    portal_stubs = [
        ("FW-AL-MES-PORTAL", "Albania Ministry of Education portal", "Ministry of Education and Sport (Albania)", "https://arsimi.gov.al/", "JUR-AL", ["sq"]),
        ("FW-AD-EDUCACIO-PORTAL", "Andorra education portal", "Ministeri d'Educació i Ensenyament Superior", "https://www.educacio.ad/", "JUR-AD", ["ca", "fr", "es"]),
        ("FW-AM-ESCS-PORTAL", "Armenia ESCS ministry portal", "Ministry of Education, Science, Culture and Sport", "https://escs.am/", "JUR-AM", ["hy"]),
        ("FW-AZ-EDU-PORTAL", "Azerbaijan Ministry of Science and Education portal", "Ministry of Science and Education", "https://edu.gov.az/", "JUR-AZ", ["az", "en"]),
        ("FW-BY-EDU-PORTAL", "Belarus Ministry of Education portal", "Ministry of Education", "https://edu.gov.by/", "JUR-BY", ["ru", "be"]),
        ("FW-BA-FRAGMENTED", "Bosnia and Herzegovina education systems (fragmented)", "Entity / canton ministries", "https://www.mcp.gov.ba/", "JUR-BA", ["bs", "hr", "sr"]),
        ("FW-BG-MON-PORTAL", "Bulgaria Ministry of Education and Science portal", "Ministry of Education and Science", "https://www.mon.bg/", "JUR-BG", ["bg"]),
        ("FW-HR-MZO-PORTAL", "Croatia MZO portal", "Ministry of Science, Education and Youth", "https://mzo.gov.hr/", "JUR-HR", ["hr"]),
        ("FW-CY-MOEC-PORTAL", "Cyprus MoEC portal", "Ministry of Education, Sport and Youth", "https://www.moec.gov.cy/", "JUR-CY", ["el", "en"]),
        ("FW-GE-MES-PORTAL", "Georgia MES portal", "Ministry of Education, Science and Youth", "https://mes.gov.ge/", "JUR-GE", ["ka", "en"]),
        ("FW-GR-MINEDU-PORTAL", "Greece Ministry of Education portal", "Ministry of Education", "https://www.minedu.gov.gr/", "JUR-GR", ["el"]),
        ("FW-HU-NAT", "Hungary National Core Curriculum (NAT) entry", "Hungarian education authorities", "https://www.oktatas.hu/", "JUR-HU", ["hu"]),
        ("FW-IS-NATIONAL-CURRICULUM", "Iceland National Curriculum Guides entry", "Ministry of Education and Children", "https://www.government.is/", "JUR-IS", ["is", "en"]),
        ("FW-XK-MASHT-PORTAL", "Kosovo MASHT portal", "Ministry of Education, Science, Technology and Innovation", "https://masht.rks-gov.net/", "JUR-XK", ["sq", "sr"]),
        ("FW-LV-IZM-PORTAL", "Latvia IZM portal", "Ministry of Education and Science", "https://www.izm.gov.lv/", "JUR-LV", ["lv"]),
        ("FW-LI-SCHULAMT", "Liechtenstein education administration entry", "Schulamt / LLV", "https://www.llv.li/", "JUR-LI", ["de"]),
        ("FW-LT-SMM-PORTAL", "Lithuania SMM portal", "Ministry of Education, Science and Sport", "https://www.smm.lt/", "JUR-LT", ["lt"]),
        ("FW-LU-MEN-PORTAL", "Luxembourg MEN portal", "Ministère de l'Éducation nationale", "https://men.public.lu/", "JUR-LU", ["fr", "de", "lb"]),
        ("FW-MT-NCF", "Malta National Curriculum / Learning Outcomes Framework entry", "Ministry for Education", "https://education.gov.mt/", "JUR-MT", ["en", "mt"]),
        ("FW-MD-MEC-PORTAL", "Moldova MEC portal", "Ministry of Education and Research", "https://mec.gov.md/", "JUR-MD", ["ro"]),
        ("FW-MC-EDUCATION", "Monaco education authority entry", "Direction de l'Éducation nationale", "https://www.gouv.mc/", "JUR-MC", ["fr"]),
        ("FW-ME-MPS-PORTAL", "Montenegro MPS portal", "Ministry of Education, Science and Innovation", "https://www.gov.me/mps", "JUR-ME", ["sr"]),
        ("FW-MK-MON-PORTAL", "North Macedonia MON portal", "Ministry of Education and Science", "https://mon.gov.mk/", "JUR-MK", ["mk", "sq"]),
        ("FW-RO-EDU-PORTAL", "Romania Ministry of Education portal", "Ministry of Education", "https://www.edu.ro/", "JUR-RO", ["ro"]),
        ("FW-RU-FSES", "Russian Federation FSES/FGOS entry", "Ministry of Education", "https://edu.gov.ru/", "JUR-RU", ["ru"]),
        ("FW-SM-ISTRUZIONE", "San Marino instruction authority entry", "Segreteria di Stato per l'Istruzione", "https://www.istruzione.sm/", "JUR-SM", ["it"]),
        ("FW-RS-PROSVETA", "Serbia Ministry of Education portal", "Ministry of Education", "https://prosveta.gov.rs/", "JUR-RS", ["sr"]),
        ("FW-SK-ISCED", "Slovakia state educational programmes entry", "Ministry of Education", "https://www.minedu.sk/", "JUR-SK", ["sk"]),
        ("FW-SI-KURIKUL", "Slovenia curriculum portal entry", "Ministry of Education", "https://www.gov.si/en/state-authorities/ministries/ministry-of-education/", "JUR-SI", ["sl", "en"]),
        ("FW-TR-MEB-PORTAL", "Türkiye MEB portal", "Ministry of National Education", "https://www.meb.gov.tr/", "JUR-TR", ["tr"]),
        ("FW-VA-VATICAN-PORTAL", "Holy See / Vatican portal entry", "Holy See", "https://www.vatican.va/", "JUR-VA", ["it", "en", "la"]),
    ]
    for fid, title, auth, url, jid, langs in portal_stubs:
        fws.append(
            _portal_fw(
                fid,
                title,
                auth,
                url,
                jid,
                language=langs,
                gaps=["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED", "TRANSLATION_REQUIRED"]
                if langs and langs[0] not in {"en"}
                else ["SOURCE_VERSION_UNCLEAR", "NOT_YET_MAPPED"],
            )
        )
    return fws


def europe_framework_patches() -> dict[str, dict]:
    """In-place upgrades for frameworks that already exist in the generator."""
    return {
        "FW-GB-SCT-CFE": {
            "title": "Curriculum for Excellence (Scotland) — Experiences and Outcomes / Early Level",
            "version": "CfE Experiences and Outcomes + Early Level Benchmarks (Education Scotland; Es&Os PDF corpus)",
            "effective_from": "2010",
            "url": "https://education.gov.scot/curriculum-for-excellence/experiences-and-outcomes/",
            "verification": "OFFICIAL_VERIFIED",
            "summary_domains": [
                "early level experiences and outcomes",
                "literacy numeracy health and wellbeing (responsibility of all)",
                "technologies / sciences curriculum areas (early level grain)",
                "benchmarks for early level",
            ],
            "gaps": [],
            "notes": "Scotland-only. Early level spans ELC and P1. Realising the Ambition supports practice: https://education.gov.scot/resources/realising-the-ambition/",
            "mandatory_baseline": True,
        },
        "FW-GB-WLS-CFW": {
            "title": "Curriculum for Wales Framework",
            "version": "Curriculum and Assessment (Wales) Act 2021 Framework + Statements of What Matters Code (2023 update, WG47535)",
            "effective_from": "2022",
            "url": "https://hwb.gov.wales/curriculum-for-wales",
            "verification": "OFFICIAL_VERIFIED",
            "summary_domains": [
                "four purposes",
                "six areas of learning and experience",
                "27 statements of what matters",
                "Science and Technology AoLE",
                "enabling learning / progression step 1",
            ],
            "gaps": [],
            "notes": "Wales-only. Statements of What Matters Code PDF: https://www.gov.wales/sites/default/files/publications/2023-06/curriculum-for-wales-statements-of-what-matters-code.pdf",
            "mandatory_baseline": True,
        },
        "FW-GB-NIR-CURRICULUM": {
            "title": "Northern Ireland Curriculum — Foundation Stage / Primary",
            "version": "The Northern Ireland Curriculum Primary (Foundation Stage Years 1–2; CCEA)",
            "effective_from": None,
            "url": "https://ccea.org.uk/foundation-stage",
            "verification": "OFFICIAL_VERIFIED",
            "summary_domains": [
                "Language and Literacy",
                "Mathematics and Numeracy",
                "The Arts",
                "The World Around Us",
                "Personal Development and Mutual Understanding",
                "Physical Development and Movement",
                "Using ICT (cross-curricular skill)",
                "Thinking Skills and Personal Capabilities",
            ],
            "gaps": [],
            "notes": "NI-only. Statutory curriculum overview also on https://www.education-ni.gov.uk/articles/statutory-curriculum",
            "age_relevance": ["K4", "K5", "K6", "K7"],
            "mandatory_baseline": True,
        },
        "FW-FI-ECEC": {
            "title": "National core curriculum for early childhood education and care (Finland)",
            "version": "National core curriculum for ECEC 2022 (OPH; EN overview + EN PDF support material)",
            "effective_from": "2022-08",
            "url": "https://www.oph.fi/en/education-and-qualifications/national-core-curriculum-ecec-nutshell",
            "verification": "OFFICIAL_VERIFIED",
            "summary_domains": [
                "educare model (care education teaching)",
                "transversal competences",
                "learning areas / pedagogical activities",
                "play as central method",
                "child's individual ECEC plan",
                "continuum to pre-primary and basic education",
            ],
            "gaps": ["TRANSLATION_REQUIRED: Finnish/Swedish normative ePerusteet text for clause-level work"],
            "notes": "English nutshell + EN PDF exist; binding norm published in Finnish/Swedish on ePerusteet.",
            "mandatory_baseline": True,
        },
        "FW-FI-BASIC": {
            "title": "National core curriculum for basic education (Finland)",
            "version": "Perusopetuksen opetussuunnitelman perusteet 2014 (implementation from 2016 grades 1–6)",
            "effective_from": "2016-08",
            "url": "https://www.oph.fi/en/education-and-qualifications/national-core-curriculum-basic-education",
            "verification": "OFFICIAL_VERIFIED",
            "summary_domains": [
                "transversal competences (incl. ICT competence)",
                "multiliteracy",
                "working life skills and entrepreneurship",
                "participation involvement and building a sustainable future",
                "subject objectives and core contents",
            ],
            "gaps": ["TRANSLATION_REQUIRED: full Finnish/Swedish normative text for clause-level work"],
            "notes": "OPH English overview verified. English print translation historically sold by OPH — do not paste.",
            "mandatory_baseline": True,
        },
        "FW-FI-DIGITAL": {
            "title": "Finland digital competence — transversal ICT in core curricula (OPH)",
            "version": "ICT competence as transversal competence in ECEC 2022 / pre-primary / basic education 2014 frameworks",
            "effective_from": "2016",
            "url": "https://www.oph.fi/en/education-and-qualifications/national-core-curriculum-basic-education",
            "verification": "OFFICIAL_VERIFIED",
            "summary_domains": [
                "ICT competence (transversal)",
                "multiliteracy",
                "safe and responsible technology use",
                "exploratory / creative digital practice (high-level)",
            ],
            "gaps": ["TRANSLATION_REQUIRED: Finnish/Swedish clause pins"],
            "notes": "Not a standalone DigComp copy — Finnish transversal competence embedded in national core curricula.",
            "mandatory_baseline": True,
        },
        "FW-EU-DIGCOMP": {
            "title": "DigComp — European Digital Competence Framework for Citizens",
            "version": "DigComp 2.2 (JRC128415; Publications Office 17 Mar 2022; DOI 10.2760/115376)",
            "effective_from": "2022-03-17",
            "url": "https://joint-research-centre.ec.europa.eu/digcomp_en",
            "verification": "OFFICIAL_VERIFIED",
            "summary_domains": [
                "1 information and data literacy",
                "2 communication and collaboration",
                "3 digital content creation",
                "4 safety",
                "5 problem solving",
            ],
            "gaps": ["NOTE: DigComp 3.0 announced Nov 2025 — remapping pending before treating 3.0 as baseline"],
            "notes": "Citizen/adult competence framework — not a kids curriculum. Kids Edition maps at adjacent grain only. Portal: https://joint-research-centre.ec.europa.eu/digcomp/digcomp-framework_en",
            "mandatory_baseline": False,
        },
    }


def europe_mappings() -> list[dict]:
    """Outcome-family deep maps for mandatory Europe baselines + replace prior NYM stubs."""
    d = DISCLAIMER
    return [
        # England EYFS — deepen beyond single play map
        {
            "mapping_id": "MAP-EYFS-UTW-TECH-KE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-ENG-EYFS-2026",
            "from_node": "Understanding the World / technology-aware early exploration (domain family)",
            "to_kids_target_id": "KE-TARGET-SYSTEMS-STABILITY",
            "kids_bands": ["K3", "K4", "K5"],
            "notes": d + " England-only EYFS grain; screen-use regard noted on 2026 GOV.UK update — not a device curriculum.",
            "reviewed_on": RETRIEVED,
        },
        # England National Curriculum Computing — outcome families
        {
            "mapping_id": "MAP-ENG-NC-COMP-ALGO-KS1",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-ENG-NC-COMPUTING",
            "from_node": "KS1 — understand algorithms; create and debug simple programs; logical reasoning",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["K5", "K6", "K7"],
            "notes": d + " England NC Computing KS1 outcome family only.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-ENG-NC-COMP-ALGO-KS2",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-ENG-NC-COMPUTING",
            "from_node": "KS2 — design programs with sequence, selection, repetition; decompose problems",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["B5", "B6", "B7", "B8", "B9", "B10"],
            "notes": d + " England NC Computing KS2 outcome family; age band is editorial bridge.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-ENG-NC-COMP-DATA",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-ENG-NC-COMPUTING",
            "from_node": "KS1–2 — collect, organise, evaluate data; use digital content",
            "to_kids_target_id": "KE-TARGET-DATA-PATTERNS",
            "kids_bands": ["K6", "K7", "B5", "B6", "B7", "B8"],
            "notes": d + " Information technology strand family — not spreadsheet literacy claim.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-ENG-NC-COMP-SAFETY",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-ENG-NC-COMPUTING",
            "from_node": "KS1–2 digital literacy — use technology safely and respectfully; recognise unacceptable content",
            "to_kids_target_id": "KE-TARGET-DIGITAL-CITIZENSHIP",
            "kids_bands": ["K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "notes": d + " E-safety outcome family at kid grain.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-ENG-NC-SCI-KE",
            "relationship": "MAPPED_TO",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-GB-ENG-NC-PRIMARY",
            "from_node": "Primary science programmes of study (working scientifically family)",
            "to_kids_target_id": "KE-TARGET-SCIENCE-PRACTICES",
            "kids_bands": ["K5", "K6", "K7", "B5", "B6", "B7"],
            "notes": d + " High-level science practices adjacent map; not NGSS equivalence.",
            "reviewed_on": RETRIEVED,
        },
        # Scotland — replace NYM
        {
            "mapping_id": "MAP-SCT-CFE-EARLY-PLAY",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-SCT-CFE",
            "from_node": "Early level Experiences and Outcomes — play-based ELC/P1 learning",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K3", "K4", "K5", "K6"],
            "notes": d + " Scotland CfE early level only — not England EYFS.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-SCT-CFE-TECH",
            "relationship": "MAPPED_TO",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-GB-SCT-CFE",
            "from_node": "Technologies curriculum area (early/first level grain)",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["K5", "K6", "K7", "B5"],
            "notes": d + " Proposed until Es&Os technology statements are line-pinned.",
            "reviewed_on": RETRIEVED,
        },
        # Wales
        {
            "mapping_id": "MAP-WLS-CFW-ENABLE",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-WLS-CFW",
            "from_node": "Enabling learning / progression toward statements of what matters (early)",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K3", "K4", "K5"],
            "notes": d + " Curriculum for Wales — not EYFS.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-WLS-CFW-SCI-TECH",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-WLS-CFW",
            "from_node": "Science and Technology AoLE — computation / design & technology family (what matters)",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["K5", "K6", "K7", "B5", "B6", "B7"],
            "notes": d + " AoLE what-matters family grain only.",
            "reviewed_on": RETRIEVED,
        },
        # Northern Ireland
        {
            "mapping_id": "MAP-NIR-FS-PLAY",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-NIR-CURRICULUM",
            "from_node": "Foundation Stage — play-based Areas of Learning",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K4", "K5", "K6"],
            "notes": d + " NI Foundation Stage only.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-NIR-FS-WAU",
            "relationship": "MAPPED_TO",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-GB-NIR-CURRICULUM",
            "from_node": "The World Around Us — science and technology family",
            "to_kids_target_id": "KE-TARGET-SCIENCE-PRACTICES",
            "kids_bands": ["K4", "K5", "K6", "K7"],
            "notes": d,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-NIR-FS-ICT",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-GB-NIR-CURRICULUM",
            "from_node": "Using ICT cross-curricular skill (Foundation Stage grain)",
            "to_kids_target_id": "KE-TARGET-DIGITAL-CITIZENSHIP",
            "kids_bands": ["K5", "K6", "K7"],
            "notes": d + " Cross-curricular ICT skill — not a separate CS PoS.",
            "reviewed_on": RETRIEVED,
        },
        # Finland — replace NYM + deepen
        {
            "mapping_id": "MAP-FI-ECEC-PLAY",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-FI-ECEC",
            "from_node": "ECEC 2022 — play-centred pedagogical activities / learning areas family",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K2", "K3", "K4", "K5"],
            "notes": d + " Based on OPH English ECEC materials; Finnish/Swedish norm still preferred for clause pins.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-FI-PREPRIM-PLAY",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-FI-PREPRIMARY",
            "from_node": "Pre-primary education — continuum from ECEC toward basic education",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K5", "K6"],
            "notes": d,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-FI-BASIC-ICT",
            "relationship": "CROSSWALKED_AGAINST",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-FI-BASIC",
            "from_node": "Basic education transversal competences — ICT competence / multiliteracy family",
            "to_kids_target_id": "KE-TARGET-DIGITAL-CITIZENSHIP",
            "kids_bands": ["K6", "K7", "B5", "B6", "B7", "B8"],
            "notes": d + " Transversal competence family — not a separate CS subject map.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-FI-DIGITAL-CITIZEN",
            "relationship": "MAPPED_TO",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-FI-DIGITAL",
            "from_node": "Digital / ICT transversal competence — safe responsible exploratory use",
            "to_kids_target_id": "KE-TARGET-DIGITAL-CITIZENSHIP",
            "kids_bands": ["K5", "K6", "K7", "B5", "B6", "B7", "B8"],
            "notes": d,
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-FI-BASIC-ALGO",
            "relationship": "MAPPED_TO",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-FI-DIGITAL",
            "from_node": "ICT transversal — exploratory problem-solving with digital tools (early grades)",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["K6", "K7", "B5", "B6"],
            "notes": d + " Proposed; Finland embeds ICT transversally rather than as England-style computing PoS.",
            "reviewed_on": RETRIEVED,
        },
        # DigComp — replace NYM
        {
            "mapping_id": "MAP-DIGCOMP-SAFETY",
            "relationship": "INFORMED_BY",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-EU-DIGCOMP",
            "from_node": "Competence area 4 — Safety (knowledge/skills/attitudes family)",
            "to_kids_target_id": "KE-TARGET-DIGITAL-CITIZENSHIP",
            "kids_bands": ["B5", "B6", "B7", "B8", "B9", "B10"],
            "notes": d + " DigComp is a citizen framework; kid-grain adaptation is editorial only.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-DIGCOMP-PROBLEM",
            "relationship": "INFORMED_BY",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-EU-DIGCOMP",
            "from_node": "Competence area 5 — Problem solving",
            "to_kids_target_id": "KE-TARGET-ALGO-FOUNDATIONS",
            "kids_bands": ["B7", "B8", "B9", "B10"],
            "notes": d + " Loose adjacent inspiration; not DigComp for Children.",
            "reviewed_on": RETRIEVED,
        },
        # IB PYP public
        {
            "mapping_id": "MAP-IB-PYP-AGENCY",
            "relationship": "INFORMED_BY",
            "fidelity": "ADJACENT",
            "from_framework_id": "FW-IB-PYP-PUBLIC",
            "from_node": "Agency / inquiry / learner pillar (public overview)",
            "to_kids_target_id": "KE-TARGET-PLAY-INQUIRY",
            "kids_bands": ["K3", "K4", "K5", "K6"],
            "notes": d + " Public IBO programme pages only; not IB authorisation or school alignment.",
            "reviewed_on": RETRIEVED,
        },
        {
            "mapping_id": "MAP-IB-PYP-THEMES",
            "relationship": "INFORMED_BY",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-IB-PYP-PUBLIC",
            "from_node": "Transdisciplinary themes / programme of inquiry (public)",
            "to_kids_target_id": "KE-TARGET-SCIENCE-PRACTICES",
            "kids_bands": ["K5", "K6", "K7", "B5", "B6"],
            "notes": d + " Theme-level public overview only.",
            "reviewed_on": RETRIEVED,
        },
        # OECD already mapped; Germany structure note via KMK — light INFORMED_BY
        {
            "mapping_id": "MAP-DE-KMK-STRUCTURE",
            "relationship": "INFORMED_BY",
            "fidelity": "PROPOSED",
            "from_framework_id": "FW-DE-KMK-PORTAL",
            "from_node": "Länder curriculum responsibility (structural note)",
            "to_kids_target_id": "KE-TARGET-COMPUTING-SOCIETY",
            "kids_bands": ["B8", "B9", "B10"],
            "notes": d + " Structural awareness only — no Land Lehrplan outcome map yet.",
            "reviewed_on": RETRIEVED,
        },
    ]


EUROPE_REGIONAL_PRIORITY_NOTE = (
    "Track 2B (2026-09-03): All Europe national rows researched to ≥IDENTIFIED; "
    "England EYFS+NC, Scotland/Wales/NI, Finland ECEC/pre-primary/basic/digital, "
    "DigComp 2.2, IB PYP public elements, and Germany 16 Länder structure pinned. "
    "No official-alignment claims."
)


EUROPE_COVERAGE_GAPS = [
    "1. **UK nations:** England EYFS + primary National Curriculum (incl. computing PoS) `OFFICIAL_VERIFIED` with outcome-family maps; Scotland CfE, Curriculum for Wales, and NI Foundation Stage `OFFICIAL_VERIFIED` as distinct systems.",
    "2. **Finland:** ECEC 2022, pre-primary, basic education 2014, and transversal digital competence `OFFICIAL_VERIFIED` via OPH English portals; Finnish/Swedish normative clause work still `TRANSLATION_REQUIRED`.",
    "3. **Germany:** KMK federal coordination `OFFICIAL_VERIFIED`; all 16 Länder `IDENTIFIED` with ministry pins — Land Lehrplan deep maps still pending (`TRANSLATION_REQUIRED`).",
    "4. **EU / OECD / IB:** DigComp 2.2 version-pinned (`OFFICIAL_VERIFIED`); DigComp 3.0 (Nov 2025) remapping pending; OECD Learning Compass retained; IB PYP public elements `IDENTIFIED` (licensed corpus not reproduced).",
    "5. **Wider Europe:** Remaining national rows advanced from `NOT_YET_RESEARCHED` to `IDENTIFIED` with ministry/portal frameworks; most deep clause maps still `NOT_YET_MAPPED` / `TRANSLATION_REQUIRED`.",
    "6. **Canada / US / world majority outside Europe:** Sister tracks own non-Europe census depth; Europe track does not claim completion elsewhere.",
    "7. **No EXACT maps yet:** Europe deep maps use `ADJACENT`/`PROPOSED` at outcome-family grain — not certification.",
    "8. **Copyright:** No wholesale standards text; domain / strand / outcome-family summaries only.",
]


def merge_mappings(existing: list[dict]) -> list[dict]:
    """Drop superseded Europe NYM stubs and append deep maps."""
    drop = {
        "MAP-FI-ECEC-NYM",
        "MAP-SCT-CFE-NYM",
        "MAP-DIGCOMP-NYM",
    }
    kept = [m for m in existing if m.get("mapping_id") not in drop]
    # Avoid duplicate IDs if regenerate called twice
    have = {m["mapping_id"] for m in kept}
    for m in europe_mappings():
        if m["mapping_id"] not in have:
            kept.append(m)
            have.add(m["mapping_id"])
    return kept


def apply_framework_patches(frameworks: list[dict]) -> list[dict]:
    patches = europe_framework_patches()
    out = []
    seen = set()
    for fw in frameworks:
        fid = fw["framework_id"]
        if fid in patches:
            merged = dict(fw)
            merged.update(patches[fid])
            out.append(merged)
        else:
            out.append(fw)
        seen.add(fid)
    for fw in europe_extra_frameworks():
        if fw["framework_id"] not in seen:
            out.append(fw)
            seen.add(fw["framework_id"])
    return out
